#
# Composite Action for PR review with Claude (Read-Write-Execute)
#
# Usage:
#   - uses: elastic/ai-github-actions/workflows/pr-review/rwx@v1
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude PR Review (Read-Write-Execute)"
description: "Review pull requests using Claude with code suggestions and test execution"

branding:
  icon: "git-pull-request"
  color: "purple"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-sonnet-4-20250514"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    # Note: Allows all Bash commands by default.
    default: "Edit,MultiEdit,Glob,Grep,LS,Read,Write,WebSearch,WebFetch,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(*),mcp__agents-md-generator__generate_agents_md,mcp__public-code-search__search_code,Bash(${{ github.action_path }}/../scripts/pr-comment.sh:*),Bash(${{ github.action_path }}/../scripts/pr-remove-comment.sh:*),Bash(${{ github.action_path }}/../scripts/pr-review.sh:*),Bash(${{ github.action_path }}/../scripts/pr-diff.sh:*)"

  extra-allowed-tools:
    description: "Additional comma-separated list of allowed tools (concatenated with allowed-tools)"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: '{"mcpServers":{"agents-md-generator":{"type":"http","url":"https://agents-md-generator.fastmcp.app/mcp"},"public-code-search":{"type":"http","url":"https://public-code-search.fastmcp.app/mcp"}}}'

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Run Claude for PR Review (Read-Write-Execute)
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_REVIEW_REPO: ${{ github.repository }}
        PR_REVIEW_PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_REVIEW_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_REVIEW_COMMENTS_DIR: /tmp/pr-review-comments
        PR_SCRIPTS: ${{ github.action_path }}/../scripts
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          <context>
          Repository: ${{ github.repository }}
          PR Number: #${{ github.event.pull_request.number }}
          PR Title: ${{ github.event.pull_request.title }}
          PR Author: ${{ github.event.pull_request.user.login }}
          Branch: ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}
          
          **Note**: The PR head branch has already been checked out. The workspace is ready for review - you can immediately start reviewing files and diffs.
          </context>

          <pr_description>
          ${{ github.event.pull_request.body }}
          </pr_description>

          <task>
          Review this pull request and provide feedback via GitHub PR review comments.
          Focus on identifying concrete issues that require action.
          Be concise, specific, and actionable. Avoid verbose explanations or praise.
          
          Use inline comments (pr-comment.sh) for line-specific issues with concrete fixes.
          Put broader architectural concerns in the review body when submitting.
          </task>

          <constraints>
          This workflow allows code suggestions via inline comments in GitHub PR review comments.
          
          You CAN: Read/analyze code, review diffs, provide code suggestions (via ```suggestion blocks), write/modify files locally to verify your recommendations work, run tests to verify fixes
          You CANNOT: Create branches, checkout branches, commit code to the repository
          Do not push changes to the repository.
          
          **Important**: You can make local code changes to verify your recommendations work, but you cannot push those changes.
          Your feedback is provided via GitHub PR review comments. Local changes are for verification/testing only.
          </constraints>

          <allowed_tools>
          You have access to the following tools (comma-separated list):
          
          ${{ inputs.allowed-tools }}
          ${{ inputs.extra-allowed-tools }}
          
          You can only use tools that are explicitly listed above. For Bash commands, the pattern `Bash(command:*)` means you can run that command with any arguments. If a command is not listed, it is not available.
          </allowed_tools>

          <getting_started>
          1. Use `mcp__agents-md-generator__generate_agents_md` to get repository context
          2. Run `$PR_SCRIPTS/pr-diff.sh` to see all changed files with diffs
             - Output shows line numbers: `[LINE]` = commentable, `[----]` = deleted (can't comment)
             - For large PRs, it will list files only - review each with `pr-diff.sh <filename>`
          3. Use `Read` to see full file contents when you need more context
          </getting_started>

          <severity_classification>
          Classify each finding by severity:

          🔴 CRITICAL - Must fix before merge
             Security vulnerabilities, data corruption risk, production-breaking bugs
             Confidence: 95-100%

          🟠 HIGH - Should fix before merge  
             Logic errors, missing validation on critical paths, significant performance issues
             Confidence: 85-94%

          🟡 MEDIUM - Address soon (non-blocking)
             Error handling gaps, suboptimal patterns, missing edge cases
             Confidence: 70-84%

          ⚪ LOW - Author discretion (non-blocking)
             Minor improvements, documentation suggestions, style preferences not covered by linters
             Confidence: Below 70%
          </severity_classification>

          <review_criteria>
          Focus your review on these categories, in priority order:

          1. Security vulnerabilities (injection, XSS, auth bypass, secrets exposure)
          2. Logic bugs that could cause runtime failures or incorrect behavior
          3. Data integrity issues (race conditions, missing transactions, corruption risk)
          4. Performance bottlenecks (N+1 queries, memory leaks, blocking operations)
          5. Error handling gaps (unhandled exceptions, missing validation)
          6. Breaking changes to public APIs without migration path
          7. Missing or incorrect test coverage for critical paths
          </review_criteria>

          <filtering_rules>
          Do NOT flag:
          - Issues in unchanged code (only review the diff)
          - Style preferences handled by linters (formatting, semicolons, indentation)
          - Subjective nitpicks without security/correctness implications
          - Code patterns that are intentional based on surrounding context
          - Pre-existing issues not introduced by this PR
          </filtering_rules>

          <review_process>
          1. Get repository context with `mcp__agents-md-generator__generate_agents_md`
          2. Run `$PR_SCRIPTS/pr-diff.sh` to see changed files with line-numbered diffs
          3. For each file, review the diff and identify issues matching review_criteria
          4. For each issue found:
             - Determine severity using severity_classification
             - Verify it's not filtered by filtering_rules
             - Use the `[LINE]` number from the diff output for pr-comment.sh
             - Provide --severity, --title, --why, and suggestion code via heredoc
             - Use --no-suggestion only for issues requiring multi-location fixes
          5. Submit review with `$PR_SCRIPTS/pr-review.sh`, including broader architectural
             concerns in the review body (not as inline comments)
          </review_process>

          <comment_format>
          The pr-comment.sh script assembles comments in a consistent format. You provide:
          - --severity: critical, high, medium, low
          - --title: Brief description for the comment heading
          - --why: One sentence explaining the risk/impact
          - Suggestion code via stdin (heredoc) - or --no-suggestion for architectural issues

          **Always provide suggestions** for line-specific issues. Use --no-suggestion only when
          the fix requires changes across multiple locations. Larger architectural concerns
          belong in the review body, not inline comments.
          </comment_format>

          <review_decision>
          Based on findings, choose the appropriate review action:

          - REQUEST_CHANGES: If any 🔴 CRITICAL or 🟠 HIGH issues found
          - COMMENT: If only 🟡 MEDIUM or ⚪ LOW issues found
          - APPROVE: If no issues found or only trivial improvements suggested

          Keep the review summary concise - the inline comments contain the details.
          </review_decision>

          <tools>
          View changed files:
          ```bash
          $PR_SCRIPTS/pr-diff.sh
          ```

          View specific file diff:
          ```bash
          $PR_SCRIPTS/pr-diff.sh path/to/file.go
          ```

          Add inline comment with suggestion (preferred):
          ```bash
          $PR_SCRIPTS/pr-comment.sh <file> <line> \
            --severity <critical|high|medium|low> \
            --title "Brief description" \
            --why "Risk or impact" <<'EOF'
          corrected code here
          EOF
          ```

          Add inline comment without suggestion (for architectural issues only):
          ```bash
          $PR_SCRIPTS/pr-comment.sh <file> <line> \
            --severity <critical|high|medium|low> \
            --title "Brief description" \
            --why "Risk or impact" \
            --no-suggestion
          ```

          Remove a queued comment (if you made a mistake):
          ```bash
          $PR_SCRIPTS/pr-remove-comment.sh <file> <line>
          ```

          Submit review (include broader concerns in the summary):
          ```bash
          $PR_SCRIPTS/pr-review.sh <APPROVE|REQUEST_CHANGES|COMMENT> "<summary>"
          ```
          
          Note: A standard footer is automatically appended to all comments and reviews.
          </tools>

          <tracking_comment>
          After submitting the review, your progress tracking comment will be updated automatically.
          Keep the final message brief - do NOT repeat the review findings or inline comments.
          Simply indicate the review was submitted, note any issues that you encountered reviewing the PR
          or using tools, and include the standard footer:

          ---
          *Review by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type `@claude` to interact further | [What is this?](https://ela.st/github-ai-tools)"
          </tracking_comment>

          <additional_instructions>
          ${{ inputs.additional-instructions }}
          </additional_instructions>
        claude_args: |
          ${{ format('--allowedTools {0}{1}', inputs.allowed-tools, inputs.extra-allowed-tools != '' && format(',{0}', inputs.extra-allowed-tools) || '') }}
          --mcp-config "${{ inputs.mcp-servers }}"
          --model ${{ inputs.model }}
