# Example workflow for automatic PR review (read-write-execute)
# Copy this to your repo's .github/workflows/ directory
#
# This version provides review comments with code suggestions.
# All Bash commands are allowed by default.

name: PR Review (Read-Write-Execute)

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      # Place environment setup commands here (e.g., install dependencies, configure tools)

      - name: Run Claude PR Review (Read-Write-Execute)
        uses: elastic/ai-github-actions/workflows/pr-review/rwx@v0
        with:
          claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github-token: ${{ github.token }}
          # Optional: add custom instructions
          # additional-instructions: "Pay special attention to security patterns"
          # Note: All Bash commands (Bash(*)) are allowed by default
          # Use extra-allowed-tools to add additional tools if needed
