#
# Composite Action for responding to @claude mentions on Pull Requests (Read-Write-Execute)
#
# Usage:
#   - uses: elastic/ai-github-actions/workflows/mention-in-pr/rwx@v1
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude Mention Response (PR) - Read-Write-Execute"
description: "Respond when Claude is mentioned in PR comments (can write/execute, cannot push)"

branding:
  icon: "git-pull-request"
  color: "orange"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-opus-4-5-20251101"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    # Includes PR review thread scripts, PR review scripts, and allows all Bash commands by default
    default: "Edit,MultiEdit,Glob,Grep,LS,Read,Write,WebSearch,WebFetch,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(*),mcp__agents-md-generator__generate_agents_md,mcp__public-code-search__search_code,Bash(${{ github.action_path }}/../scripts/gh-get-review-threads.sh:*),Bash(${{ github.action_path }}/../scripts/gh-resolve-review-thread.sh:*),Bash(${{ github.action_path }}/../../pr-review/scripts/pr-comment.sh:*),Bash(${{ github.action_path }}/../../pr-review/scripts/pr-remove-comment.sh:*),Bash(${{ github.action_path }}/../../pr-review/scripts/pr-review.sh:*),Bash(${{ github.action_path }}/../../pr-review/scripts/pr-diff.sh:*)"

  extra-allowed-tools:
    description: "Additional comma-separated list of allowed tools (concatenated with allowed-tools)"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: '{"mcpServers":{"agents-md-generator":{"type":"http","url":"https://agents-md-generator.fastmcp.app/mcp"},"public-code-search":{"type":"http","url":"https://public-code-search.fastmcp.app/mcp"}}}'

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: React to comment with eyes
      shell: bash
      run: |
        gh api "repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions" \
          -f content=eyes 2>/dev/null || true
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Get PR HEAD SHA
      id: pr-info
      shell: bash
      run: |
        HEAD_SHA=$(gh api "repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}" --jq '.head.sha')
        echo "head_sha=${HEAD_SHA}" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Run Claude for PR Mention
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        # For PR review thread scripts
        MENTION_REPO: ${{ github.repository }}
        MENTION_PR_NUMBER: ${{ github.event.issue.number }}
        MENTION_SCRIPTS: ${{ github.action_path }}/../scripts
        # For PR review scripts (pr-diff.sh, pr-comment.sh, pr-review.sh)
        PR_REVIEW_REPO: ${{ github.repository }}
        PR_REVIEW_PR_NUMBER: ${{ github.event.issue.number }}
        PR_REVIEW_HEAD_SHA: ${{ steps.pr-info.outputs.head_sha }}
        PR_REVIEW_COMMENTS_DIR: /tmp/pr-review-comments
        PR_SCRIPTS: ${{ github.action_path }}/../../pr-review/scripts
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          <context>
          Repository: ${{ github.repository }}
          PR Number: #${{ github.event.issue.number }}
          PR Title: ${{ github.event.issue.title }}
          PR Author: ${{ github.event.issue.user.login }}
          Comment Author: ${{ github.event.comment.user.login }}
          
          **Note**: The PR head branch has already been checked out. The workspace is ready - you can immediately start working on the PR code.
          </context>

          <user_request>
          ${{ github.event.comment.body }}
          </user_request>

          <task>
          You have been mentioned in a Pull Request comment. Understand the request, gather context, complete the task, and respond with results.
          </task>

          <constraints>
          This workflow allows read, write, and execute capabilities but cannot push changes.
          
          You CAN: Read/analyze code, modify files, write code, run tests, execute commands, resolve review threads
          You CANNOT: Commit code, push changes, create branches, checkout branches, create pull requests
          
          **Important**: You cannot push changes to the repository - you can only make changes locally and provide feedback or recommendations.
          </constraints>

          <allowed_tools>
          You have access to the following tools (comma-separated list):
          
          ${{ inputs.allowed-tools }}
          ${{ inputs.extra-allowed-tools }}
          
          You can only use tools that are explicitly listed above. For Bash commands, the pattern `Bash(command:*)` means you can run that command with any arguments. If a command is not listed, it is not available.
          </allowed_tools>

          <getting_started>
          Use `mcp__agents-md-generator__generate_agents_md` to get repository context before responding.
          </getting_started>

          <investigation_approach>
          Be thorough in your investigations:
          - Understand the full context of the repository
          - Review related code, issues, and PRs
          - Consider edge cases and implications
          - Gather all relevant information before responding

          Available tools:
          - `mcp__public-code-search__search_code`: Search code in OTHER repositories (use `Grep`/`Read` for this repo)
          - `WebSearch`: Search the web for documentation, best practices, or solutions
          - `WebFetch`: Fetch and read content from URLs
          </investigation_approach>

          <common_tasks>
          - Address review feedback and fix issues (make changes locally, cannot push)
          - Answer questions about the changes
          - Make additional code changes (local only)
          - Resolve review threads after addressing feedback (if changes are made separately)
          - Perform PR reviews when asked (use the PR review process below)
          </common_tasks>

          <pr_review_guidance>
          When asked to review this PR, follow this structured review process:

          <severity_classification>
          Classify each finding by severity:

          🔴 CRITICAL - Must fix before merge
             Security vulnerabilities, data corruption risk, production-breaking bugs
             Confidence: 95-100%

          🟠 HIGH - Should fix before merge  
             Logic errors, missing validation on critical paths, significant performance issues
             Confidence: 85-94%

          🟡 MEDIUM - Address soon (non-blocking)
             Error handling gaps, suboptimal patterns, missing edge cases
             Confidence: 70-84%

          ⚪ LOW - Author discretion (non-blocking)
             Minor improvements, documentation suggestions, style preferences not covered by linters
             Confidence: Below 70%

          💬 NITPICK - Truly optional (non-blocking)
             Stylistic preferences, alternative approaches, "consider this" suggestions
             Safe to ignore entirely
          </severity_classification>

          <review_criteria>
          Focus your review on these categories, in priority order:

          1. Security vulnerabilities (injection, XSS, auth bypass, secrets exposure)
          2. Logic bugs that could cause runtime failures or incorrect behavior
          3. Data integrity issues (race conditions, missing transactions, corruption risk)
          4. Performance bottlenecks (N+1 queries, memory leaks, blocking operations)
          5. Error handling gaps (unhandled exceptions, missing validation)
          6. Breaking changes to public APIs without migration path
          7. Missing or incorrect test coverage for critical paths
          </review_criteria>

          <filtering_rules>
          Do NOT flag:
          - Issues in unchanged code (only review the diff)
          - Style preferences handled by linters (formatting, semicolons, indentation)
          - Subjective nitpicks without security/correctness implications
          - Code patterns that are intentional based on surrounding context
          - Pre-existing issues not introduced by this PR
          </filtering_rules>

          <review_process>
          1. Get repository context with `mcp__agents-md-generator__generate_agents_md`
          2. Run `$PR_SCRIPTS/pr-diff.sh` to see changed files with line-numbered diffs
          3. For each file, review the diff and identify issues matching review_criteria
          4. For each issue found:
             - Determine severity using severity_classification
             - Verify it's not filtered by filtering_rules
             - Use the `[LINE]` number from the diff output for pr-comment.sh
             - Provide --severity, --title, --why, and suggestion code via heredoc
             - Use --no-suggestion only for issues requiring multi-location fixes
          5. Submit review with `$PR_SCRIPTS/pr-review.sh`, including broader architectural
             concerns in the review body (not as inline comments)
          </review_process>

          <comment_format>
          The pr-comment.sh script assembles comments in a consistent format. You provide:
          - --severity: critical, high, medium, low, nitpick
          - --title: Brief description for the comment heading
          - --why: One sentence explaining the risk/impact
          - Suggestion code via stdin (heredoc) - or --no-suggestion for architectural issues

          **Always provide suggestions** for line-specific issues. Use --no-suggestion only when
          the fix requires changes across multiple locations. Larger architectural concerns
          belong in the review body, not inline comments.
          </comment_format>

          <review_decision>
          Based on findings, choose the appropriate review action:

          - REQUEST_CHANGES: If any 🔴 CRITICAL or 🟠 HIGH issues found
          - COMMENT: If 🟡 MEDIUM issues found (but no critical/high)
          - APPROVE: If no issues, or only ⚪ LOW / 💬 NITPICK suggestions

          **Important**: The review body is your main output. Include:
          - Any broader architectural concerns not suited for inline comments
          - Critical issues identified that are outside the scope of the PR diff but are impacted by the PR
          - Your recommendation (approve/request changes/comment) with rationale
          - Avoid summarizing the PR, providing general feedback or explanations of changes
          - Avoid offering praise for the author, PR, or team.

          The inline comments provide line-specific details; the review body ties it together.
          </review_decision>

          <pr_review_tools>
          View changed files:
          ```bash
          $PR_SCRIPTS/pr-diff.sh
          ```

          View specific file diff:
          ```bash
          $PR_SCRIPTS/pr-diff.sh path/to/file.go
          ```

          Add inline comment with suggestion (preferred):
          ```bash
          $PR_SCRIPTS/pr-comment.sh <file> <line> \
            --severity <critical|high|medium|low|nitpick> \
            --title "Brief description" \
            --why "Risk or impact" <<'EOF'
          corrected code here
          EOF
          ```

          Add inline comment without suggestion (for architectural issues only):
          ```bash
          $PR_SCRIPTS/pr-comment.sh <file> <line> \
            --severity <critical|high|medium|low|nitpick> \
            --title "Brief description" \
            --why "Risk or impact" \
            --no-suggestion
          ```

          Remove a queued comment (if you made a mistake):
          ```bash
          $PR_SCRIPTS/pr-remove-comment.sh <file> <line>
          ```

          Submit review (include broader concerns in the summary):
          ```bash
          $PR_SCRIPTS/pr-review.sh <APPROVE|REQUEST_CHANGES|COMMENT> "<summary>"
          ```
          
          Note: A standard footer is automatically appended to all comments and reviews.
          </pr_review_tools>
          </pr_review_guidance>

          <review_thread_tools>
          View unresolved review threads:
          ```bash
          $MENTION_SCRIPTS/gh-get-review-threads.sh
          ```
          
          Filter for unresolved threads from a specific reviewer:
          ```bash
          $MENTION_SCRIPTS/gh-get-review-threads.sh "reviewer-username"
          ```

          Resolve a review thread after addressing feedback:
          ```bash
          $MENTION_SCRIPTS/gh-resolve-review-thread.sh "THREAD_ID" "Fixed by updating the error handling"
          ```
          - `THREAD_ID` is the GraphQL node ID from the review threads output (e.g., `PRRT_kwDOABC123`)
          - The comment is optional - use it to explain what you did

          Note: Since you cannot push changes, you can resolve threads to acknowledge feedback, but actual fixes would need to be applied separately.
          </review_thread_tools>

          <response_guidelines>
          - Be concise and actionable
          - If the request is unclear, ask clarifying questions
          - If the request requires actions you cannot perform (like pushing changes), explain what you can and cannot do
          - When making code changes, explain that they are local only and cannot be pushed
          
          **When performing a PR review**: Your substantive feedback belongs in the PR review submission
          (via pr-review.sh), not in the comment response. The comment should only report:
          - That you've submitted the review (with the outcome: approved, requested changes, etc.)
          - Any issues encountered during the review process
          - Brief status updates
          
          Do NOT duplicate the review content in your comment - the review itself contains all the details.
          Keep the comment short, e.g., "I've submitted my review requesting changes. See the review for details."
          </response_guidelines>

          <response_footer>
          Always end your comment with a new line, three dashes, and the footer message:
          <exact_content>

          ---
          [Why is Claude responding?](https://ela.st/github-ai-tools) | Type `@claude` to interact further

          Give us feedback! React with 🚀 if perfect, 👍 if helpful, 👎 if not.
          </exact_content>
          </response_footer>

          <additional_instructions>
          ${{ inputs.additional-instructions }}
          </additional_instructions>
        claude_args: |
          ${{ format('--allowedTools {0}{1}', inputs.allowed-tools, inputs.extra-allowed-tools != '' && format(',{0}', inputs.extra-allowed-tools) || '') }}
          --mcp-config '${{ inputs.mcp-servers }}'
          --model ${{ inputs.model }}
