#
# Composite Action for triaging new issues with Claude
#
# Usage:
#   - uses: your-org/ai-github-actions/workflows/issue-triage@v1
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude Issue Triage"
description: "Automatically triage and label new issues using Claude"

branding:
  icon: "tag"
  color: "blue"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-sonnet-4-20250514"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    default: "Glob,Grep,LS,Read,WebSearch,WebFetch,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(git show:*),Bash(git branch:*),Bash(git tag:*),mcp__agents-md-generator__generate_agents_md,mcp__agents-md-generator,mcp__public-code-search__search_code"

  extra-allowed-tools:
    description: "Additional comma-separated list of allowed tools (concatenated with allowed-tools)"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: '{"mcpServers":{"agents-md-generator":{"type":"http","url":"https://agents-md-generator.fastmcp.app/mcp"},"public-code-search":{"type":"http","url":"https://public-code-search.fastmcp.app/mcp"}}}'

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Run Claude for Issue Triage
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          ## GitHub Context
          - Repository: ${{ github.repository }}
          - Issue Number: #${{ github.event.issue.number }}
          - Issue Title: ${{ github.event.issue.title }}
          - Issue Author: ${{ github.event.issue.user.login }}
          - Issue Body:
          ```
          ${{ github.event.issue.body }}
          ```

          ## Instructions

          ### Important: Investigation and Planning Only
          **This workflow is for investigation and planning ONLY. You CANNOT:**
          - Create branches
          - Push changes
          - Commit code
          - Modify files
          - Make any code changes

          **You CAN:**
          - Read and analyze code
          - Search the repository
          - Review git history (`git log`, `git diff`, `git show`)
          - Check git status and branch information
          - Search for similar issues and PRs
          - Provide analysis, suggestions, and recommendations

          ### Getting Started
          **First, get repository context**: Use the `mcp__agents-md-generator__generate_agents_md` tool to generate a repository summary. This will give you essential context about the codebase structure, technologies used, and project conventions. Call this tool at the start of your investigation.

          **If you encounter any issues using tools** (e.g., tool not found, permission errors, API failures), mention this in your response with a link to the support channel: https://elastic.slack.com/archives/C0AAMNAA89M

          ### Investigation Approach
          **Be extremely thorough in your investigations**. Don't rush to conclusions. Take time to:
          - Understand the full context of the repository
          - Review related code, issues, and PRs
          - Consider edge cases and implications
          - Gather all relevant information before responding

          **Available tools for investigation**:
          - **`mcp__public-code-search__search_code`**: Use this to search for code patterns in OTHER repositories (external libraries, modules, or dependencies). The current repository is cloned locally, so use `Grep` or `Read` for searching within this repo. Use `search_code` for finding similar implementations in other projects or understanding how other repositories handle similar issues.
          - **`WebSearch`**: Use for searching the web for documentation, best practices, or solutions.
          - **`WebFetch`**: Use to fetch and read content from URLs (documentation, API references, etc.).
          - **Read-only git commands**: You can use `git status`, `git diff`, `git log`, `git show`, `git branch` to investigate the codebase, but you cannot create branches, commit, or push.

          You are triaging this new GitHub issue. Please:

          1. **Analyze the issue** - Read the title and description carefully
          2. **Categorize** - Determine if this is a bug report, feature request, question, or documentation issue
          3. **Assess priority** - Based on severity and impact
          4. **Suggest labels** - Recommend appropriate labels for this issue
          5. **Check for duplicates** - Search for similar existing issues
          6. **Respond** - Post a helpful comment that:
             - Acknowledges the issue
             - Asks clarifying questions if needed
             - Provides any immediately relevant information
             - Sets expectations for next steps

          Be helpful and welcoming to contributors.

          ## Response Footer
          Always end your comment with this footer (using markdown):
          ```
          ---
          *Comment by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type `@claude` to interact further
          ```

          ${{ inputs.additional-instructions }}
        claude_args: |
          ${{ format('--allowedTools {0}{1}', inputs.allowed-tools, inputs.extra-allowed-tools != '' && format(',{0}', inputs.extra-allowed-tools) || '') }}
          --mcp-config "${{ inputs.mcp-servers }}"
          --model ${{ inputs.model }}
