# Example workflow for @claude mentions on issues
# Copy this to your repo's .github/workflows/ directory

name: Claude Mention (Issue)

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  respond:
    # Only respond to trusted contributors (adjust list as needed)
    if: >-
      contains(github.event.comment.body, '@claude') &&
      github.event.issue.pull_request == null &&
      contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      # Place environment setup commands here (e.g., install dependencies, configure tools)
      - uses: elastic/ai-github-actions/workflows/mention-in-issue/rwxp@v0
        with:
          claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github-token: ${{ github.token }}
