# Example workflow for GitHub Actions build failure analysis
# Copy this to your repo's .github/workflows/ directory

name: Build Failure Analysis

on:
  workflow_run:
    workflows: ["CI", "Build", "Test"]  # Names of workflows to monitor
    types: [completed]

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write

jobs:
  analyze:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Claude Build Failure Analysis
        uses: your-org/ai-github-actions/workflows/build-failure-github-actions@v1
        with:
          claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
          github-token: ${{ github.token }}
