#
# Composite Action for analyzing Buildkite CI build failures with Claude
#
# Usage:
#   - uses: your-org/ai-github-actions/workflows/build-failure-buildkite@v1
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#       buildkite-api-token: ${{ secrets.BUILDKITE_API_TOKEN }}
#
name: "Claude Buildkite Build Failure Analysis"
description: "Analyze Buildkite CI build failures and suggest fixes using Claude"

branding:
  icon: "alert-triangle"
  color: "red"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  buildkite-api-token:
    description: "Buildkite API token for accessing build logs"
    required: true

  buildkite-org:
    description: "Buildkite organization slug"
    required: false
    default: "elastic"

  buildkite-pipeline:
    description: "Buildkite pipeline slug (optional - auto-discovered from repo name if not provided)"
    required: false
    default: ""

  buildkite-build-number:
    description: "Buildkite build number (optional - auto-discovered from commit SHA if not provided)"
    required: false
    default: ""

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-sonnet-4-20250514"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    default: "Edit,MultiEdit,Glob,Grep,LS,Read,Write,WebSearch,WebFetch,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(git add:*),Bash(git commit:*),Bash(git push:*),Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(git rm:*),Bash,mcp__agents-md-generator__generate_agents_md,mcp__agents-md-generator,mcp__public-code-search__search_code,mcp__buildkite"

  extra-allowed-tools:
    description: "Additional comma-separated list of allowed tools (concatenated with allowed-tools)"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "Additional MCP server configuration JSON (merged with defaults)"
    required: false
    default: ""

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Setup MCP Server Configuration
      id: mcp-config
      shell: bash
      env:
        BUILDKITE_API_TOKEN: ${{ inputs.buildkite-api-token }}
        ADDITIONAL_MCP: ${{ inputs.mcp-servers }}
      run: |
        mkdir -p /tmp/mcp-config
        
        # Start with default servers and always include Buildkite
        cat > /tmp/mcp-config/mcp-servers.json << EOF
        {
          "mcpServers": {
            "agents-md-generator": {
              "type": "http",
              "url": "https://agents-md-generator.fastmcp.app/mcp"
            },
            "public-code-search": {
              "type": "http",
              "url": "https://public-code-search.fastmcp.app/mcp"
            },
            "buildkite": {
              "type": "http",
              "url": "https://mcp.buildkite.com/mcp/readonly",
              "headers": {
                "Authorization": "Bearer $BUILDKITE_API_TOKEN"
              }
            }
          }
        }
        EOF
        
        # Merge additional MCP servers if provided
        if [ -n "$ADDITIONAL_MCP" ]; then
          echo "$ADDITIONAL_MCP" > /tmp/mcp-config/additional.json
          jq -s '.[0] * .[1]' /tmp/mcp-config/mcp-servers.json /tmp/mcp-config/additional.json > /tmp/mcp-config/mcp-servers-merged.json
          mv /tmp/mcp-config/mcp-servers-merged.json /tmp/mcp-config/mcp-servers.json
          rm /tmp/mcp-config/additional.json
        fi

    - name: Run Claude for Buildkite Build Failure Analysis
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          ## GitHub Context
          - Repository: ${{ github.repository }}
          - Event: ${{ github.event_name }}
          - Branch: ${{ github.event.workflow_run.head_branch || github.head_ref || github.ref_name }}
          - Commit SHA: ${{ github.event.workflow_run.head_sha || github.sha }}
          ${{ github.event.workflow_run.name && format('- Failed Workflow: {0}', github.event.workflow_run.name) || '' }}
          ${{ github.event.workflow_run.id && format('- Workflow Run ID: {0}', github.event.workflow_run.id) || '' }}
          ${{ github.event.workflow_run.html_url && format('- Workflow URL: {0}', github.event.workflow_run.html_url) || '' }}

          ## Buildkite Configuration
          - Organization: `${{ inputs.buildkite-org }}`
          ${{ inputs.buildkite-pipeline != '' && format('- Pipeline: `{0}` (provided)', inputs.buildkite-pipeline) || format('- Pipeline: **Auto-discover from repo name** (use `list_pipelines` for organization `{0}` to find pipelines matching repository `{1}`)', inputs.buildkite-org, github.repository) }}
          ${{ inputs.buildkite-build-number != '' && format('- Build Number: `{0}` (provided)', inputs.buildkite-build-number) || format('- Build Number: **Auto-discover from commit SHA** (use `list_builds` to find builds matching commit SHA `{0}` or on branch `{1}`)', github.event.workflow_run.head_sha || github.sha, github.event.workflow_run.head_branch || github.head_ref || github.ref_name) }}

          ## Instructions
          
          ### Getting Started
          **First, get repository context**: Use the `mcp__agents-md-generator__generate_agents_md` tool to generate a repository summary. This will give you essential context about the codebase structure, technologies used, and project conventions. Call this tool at the start of your investigation.

          **If you encounter any issues using tools** (e.g., tool not found, permission errors, API failures), mention this in your response with a link to the support channel: https://elastic.slack.com/archives/C0AAMNAA89M

          ### Investigation Approach
          **Be extremely thorough in your investigations**. Don't rush to conclusions. Take time to:
          - Understand the full context of the repository
          - Review all relevant code, build configurations, and test files
          - Analyze error messages and stack traces completely
          - Consider all possible root causes and edge cases
          - Gather comprehensive information before suggesting fixes
          
          **Available tools for investigation**:
          - **`mcp__buildkite`**: You have access to the Buildkite MCP server. Use it to query build information, job logs, and annotations.
          - **`mcp__public-code-search__search_code`**: Use this to search for code patterns in OTHER repositories (external libraries, modules, or dependencies). The current repository is cloned locally, so use `Grep` or `Read` for searching within this repo. Use `search_code` for finding similar error patterns in other projects, checking library documentation, or understanding how other repositories handle similar build issues.
          - **`WebSearch`**: Use for searching the web for error messages, build failures, or solutions to specific CI/CD problems.
          - **`WebFetch`**: Use to fetch and read content from URLs (documentation, error logs, API references, etc.).

          A Buildkite CI build has failed. Please analyze the failure and help fix it.

          ### Buildkite Analysis Workflow

          You have access to the Buildkite MCP server. Follow these steps:

          #### Step 1: Find the pipeline
          ${{ inputs.buildkite-pipeline != '' && format('Use the provided pipeline: `{0}`', inputs.buildkite-pipeline) || format('Use `list_pipelines` for organization `{0}` to find pipelines. Look for a pipeline matching the repository `{1}`. Common patterns: the pipeline slug often matches the repo name or uses the full `org/repo` format.', inputs.buildkite-org, github.repository) }}

          #### Step 2: Find the failed build
          ${{ inputs.buildkite-build-number != '' && format('Use the provided build number: `{0}`', inputs.buildkite-build-number) || format('Use `list_builds` to find builds. Look for a build matching commit SHA `{0}` or on branch `{1}`. Use the most recent failed build if multiple matches.', github.event.workflow_run.head_sha || github.sha, github.event.workflow_run.head_branch || github.head_ref || github.ref_name) }}

          #### Step 3: Get build details
          Once you have the build number, use `get_build` with:
          - Organization: `${{ inputs.buildkite-org }}`
          - Pipeline: (from step 1)
          - Build number: (from step 2)

          This will show you all jobs and their statuses. Note which jobs failed.

          #### Step 4: Analyze failed jobs
          For each failed job:
          1. Use `get_job_logs` to retrieve the full logs
          2. Use `search_logs` with patterns like `error|Error|ERROR`, `failed|Failed|FAILED`, `panic|exception`
          3. Use `tail_logs` to see the last 100 lines

          #### Step 5: Check annotations
          Use `list_annotations` to see any build annotations with errors/warnings.

          ### Analysis Steps
          1. **Identify failed jobs** - Determine exactly which Buildkite jobs failed
          2. **Extract error messages** - Find the specific error messages and stack traces from the job logs
          3. **Identify root cause** - Determine what caused the failure (code bug, test failure, dependency issue, infrastructure problem, etc.)
          4. **Analyze the code** - Look at the relevant source files in this repository
          5. **Suggest fixes** - Provide specific, actionable suggestions to resolve the issue

          ### Response Format
          Post a comment summarizing:
          - **Build**: Link to the Buildkite build
          - **What failed**: Which job(s) failed
          - **Error message**: The key error message(s) from the logs
          - **Root cause**: What caused the failure
          - **Recommended fix**: Specific steps to resolve the issue
          - **Code changes**: If applicable, show the exact code changes needed

          Focus on being helpful and specific. If the fix is straightforward, explain exactly what needs to change.

          ## Response Footer
          Always end your comment with this footer (using markdown):
          ```
          ---
          *Comment by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type `@claude` to interact further
          ```

          ${{ inputs.additional-instructions }}
        claude_args: |
          ${{ format('--allowedTools {0}{1}', inputs.allowed-tools, inputs.extra-allowed-tools != '' && format(',{0}', inputs.extra-allowed-tools) || '') }}
          --mcp-config /tmp/mcp-config/mcp-servers.json
          --model ${{ inputs.model }}
