#
# Composite Action for PR review with Claude (Read-Only)
#
# Usage:
#   - uses: elastic/ai-github-actions/workflows/pr-review/ro@v0
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude PR Review (Read-Only)"
description: "Review pull requests using Claude (read-only, comments only)"

branding:
  icon: "git-pull-request"
  color: "blue"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-opus-4-5-20251101"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    # Note: Using ${{ github.action_path }}/../scripts for the shared PR review scripts
    default: "Glob,Grep,LS,Read,WebSearch,WebFetch,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(git show:*),Bash(git tag:*),mcp__agents-md-generator__generate_agents_md,mcp__public-code-search__search_code,Bash(${{ github.action_path }}/../scripts/pr-comment.sh:*),Bash(${{ github.action_path }}/../scripts/pr-remove-comment.sh:*),Bash(${{ github.action_path }}/../scripts/pr-review.sh:*),Bash(${{ github.action_path }}/../scripts/pr-diff.sh:*),Bash(${{ github.action_path }}/../scripts/pr-existing-comments.sh:*),Bash(${{ github.action_path }}/../scripts/pr-prior-reviews.sh:*)"

  extra-allowed-tools:
    description: "Additional comma-separated list of allowed tools (concatenated with allowed-tools)"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "false"

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: '{"mcpServers":{"agents-md-generator":{"type":"http","url":"https://agents-md-generator.fastmcp.app/mcp"},"public-code-search":{"type":"http","url":"https://public-code-search.fastmcp.app/mcp"}}}'

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: React to PR with eyes
      shell: bash
      run: |
        gh api "repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/reactions" \
          -f content=eyes 2>/dev/null || true
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Run Claude for PR Review (Read-Only)
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_REVIEW_REPO: ${{ github.repository }}
        PR_REVIEW_PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_REVIEW_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_REVIEW_COMMENTS_DIR: /tmp/pr-review-comments
        PR_REVIEW_HELPERS_DIR: ${{ github.action_path }}/../scripts
      uses: elastic/ai-github-claude-code-action@working-forks
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          <context>
          You are an expert software engineer working on a PR Review for an important project.

          Repository: ${{ github.repository }}
          PR Number: #${{ github.event.pull_request.number }}
          PR Title: ${{ github.event.pull_request.title }}
          PR Author: ${{ github.event.pull_request.user.login }}
          Branch: ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}
          
          **Note**: The PR head branch has already been checked out. The workspace is ready for review - you can immediately start reviewing files and diffs.
          </context>

          <pr_description>
          ${{ github.event.pull_request.body }}
          </pr_description>

          <task>
          Review this pull request and provide feedback via GitHub PR review comments.
          Focus on identifying concrete issues that require action.
          Be concise, specific, and actionable. Avoid verbose explanations or praise.
          
          Use inline comments (pr-comment.sh) for line-specific issues with concrete fixes.
          Put broader architectural concerns in the review body when submitting.
          </task>

          <constraints>
          This workflow is for review and comments ONLY - feedback is provided via GitHub PR review comments.
          
          You CANNOT: Modify files locally, run tests, execute commands, create branches, commit code, push changes
          You CAN: Read/analyze code, review diffs, provide code suggestions (via ```suggestion blocks in comments)
          
          **Important**: Your feedback is provided via GitHub PR review comments, not by making local code changes.
          Suggestion blocks let PR authors apply your fixes with one click.
          </constraints>

          <allowed_tools>
          You have access to the following tools (comma-separated list):
          
          ${{ inputs.allowed-tools }}
          ${{ inputs.extra-allowed-tools }}
          
          You can only use tools that are explicitly listed above. For Bash commands, the pattern `Bash(command:*)` means you can run that command with any arguments. If a command is not listed, it is not available.
          </allowed_tools>

          <review_process>
          Follow these steps in order:

          **Step 1: Gather context**
          - Use `mcp__agents-md-generator__generate_agents_md` to get repository context
            (if this fails, explore the repository to understand the codebase — read key files like README, CONTRIBUTING, etc.)
          - Run `$PR_REVIEW_HELPERS_DIR/pr-prior-reviews.sh` to see prior review submissions (review body summaries)
          - Run `$PR_REVIEW_HELPERS_DIR/pr-existing-comments.sh --summary` to see existing inline review threads per file
          - Run `$PR_REVIEW_HELPERS_DIR/pr-diff.sh` to see changed files with line-numbered diffs
            (for large PRs, this lists files only — review each with `pr-diff.sh <filename>`)

          **Step 2: Review each file**
          For each changed file:
          a. If the summary showed existing threads for this file, first run:
             `$PR_REVIEW_HELPERS_DIR/pr-existing-comments.sh --file <path>`
             Read the full thread details. The output uses these conventions:
             - `← has replies` — a conversation happened; read carefully before commenting
             - `[truncated]` — comment was cut short; add `--full` if you need the complete text to understand the comment
             - `[abc1234]` — commit the comment was made on; use `git show abc1234` if needed
             - `~42` — approximate line from an older revision (exact line no longer maps to current diff)
          b. Review the diff. Use `Read` to see full file contents when you need more context.
             Identify issues matching review_criteria. Do NOT flag:
             - Issues in unchanged code (only review the diff)
             - Style preferences handled by linters
             - Pre-existing issues not introduced by this PR
             - Issues already covered by existing threads (see below)
          
          Before flagging any issue, verify it against the actual code:
          - Read the full file, not just the diff — the issue may be handled elsewhere.
          - Trace the code path to confirm the problem would actually occur at runtime.
          - If you're claiming something is missing or broken, find the evidence in the code.
          If the issue depends on assumptions you haven't confirmed, do not flag it.

          **Existing thread rules** (check BEFORE leaving any comment):
          - Resolved with reviewer reply → reviewer's decision is final. Do NOT re-flag.
            Examples: "It should remain as X", "This is intentional", "No need to do this change"
          - Resolved without reply → author likely fixed it. Do NOT re-raise unless the fix introduced a new problem.
          - Unresolved → already flagged. Do NOT re-comment. Mention in review body if you have more to add.
          - Outdated → code changed. Only re-flag if the issue still applies to the current diff.
          When in doubt, do not duplicate. Redundant comments erode trust in the review process.

          **Prior review rules** (check BEFORE writing your review body):
          - If prior reviews from this bot exist, read them carefully. Do NOT repeat points already made.
          - Only include genuinely new observations in your review body.
          - If all your observations were already covered in prior reviews, omit the review body entirely.
          - If a prior review raised a point and the author responded/addressed it, do not re-raise it.

          **Step 3: Leave comments for NEW issues only**
          Only flag issues you are confident are real problems — false positives erode trust.
          For each genuinely new issue not covered by existing threads or prior reviews:
          ```bash
          $PR_REVIEW_HELPERS_DIR/pr-comment.sh <file> <line> \
            --severity <critical|high|medium|low|nitpick> \
            --title "Brief description" \
            --why "Risk or impact" <<'EOF'
          corrected code here
          EOF
          ```
          Always provide suggestion code. Use `--no-suggestion` only when the fix requires
          changes across multiple locations. Broader architectural concerns belong in the
          review body, not inline comments.

          To remove a queued comment: `$PR_REVIEW_HELPERS_DIR/pr-remove-comment.sh <file> <line>`

          **Step 4: Submit the review**
          ```bash
          $PR_REVIEW_HELPERS_DIR/pr-review.sh <APPROVE|REQUEST_CHANGES|COMMENT> "<review body>"
          ```
          - REQUEST_CHANGES: Any 🔴 CRITICAL or 🟠 HIGH issues found
          - COMMENT: 🟡 MEDIUM issues found (but no critical/high)
          - APPROVE: No issues, or only ⚪ LOW / 💬 NITPICK suggestions

          The review body should include broader architectural concerns not suited for inline comments.
          Avoid summarizing the PR or offering praise. If approving with no issues, omit the review body.
          A standard footer is automatically appended to all comments and reviews.
          </review_process>

          <severity_classification>
          🔴 CRITICAL - Must fix before merge (security vulnerabilities, data corruption, production-breaking bugs)
          🟠 HIGH - Should fix before merge (logic errors, missing validation, significant performance issues)
          🟡 MEDIUM - Address soon, non-blocking (error handling gaps, suboptimal patterns, missing edge cases)
          ⚪ LOW - Author discretion, non-blocking (minor improvements, documentation, style not covered by linters)
          💬 NITPICK - Truly optional (stylistic preferences, alternative approaches — safe to ignore)
          </severity_classification>

          <review_criteria>
          Focus on these categories, in priority order:
          1. Security vulnerabilities (injection, XSS, auth bypass, secrets exposure)
          2. Logic bugs that could cause runtime failures or incorrect behavior
          3. Data integrity issues (race conditions, missing transactions, corruption risk)
          4. Performance bottlenecks (N+1 queries, memory leaks, blocking operations)
          5. Error handling gaps (unhandled exceptions, missing validation)
          6. Breaking changes to public APIs without migration path
          7. Missing or incorrect test coverage for critical paths
          </review_criteria>

          <github_formatting>
          When writing GitHub comments, wrap branch names, tags, or other @-references in backticks (e.g., `@main`, `@v1.0`) to avoid accidentally pinging users. Do not add backticks around terms that are already inside backticks or code blocks.
          </github_formatting>

          <additional_instructions>
          ${{ inputs.additional-instructions }}
          </additional_instructions>
        claude_args: |
          ${{ format('--allowedTools {0}{1}', inputs.allowed-tools, inputs.extra-allowed-tools != '' && format(',{0}', inputs.extra-allowed-tools) || '') }}
          --mcp-config '${{ inputs.mcp-servers }}'
          --model ${{ inputs.model }}
