# Example workflow for automatic PR review (read-only)
# Copy this to your repo's .github/workflows/ directory
#
# This version provides review comments with suggestion blocks, but cannot modify files locally or run tests.

name: PR Review (Read-Only)

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  issues: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      # Place environment setup commands here (e.g., install dependencies, configure tools)

      - name: Run Claude PR Review (Read-Only)
        uses: elastic/ai-github-actions/claude-workflows/pr-review/ro@v0
        with:
          claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github-token: ${{ github.token }}
          # Optional: add custom instructions
          # additional-instructions: "Pay special attention to security patterns"
