#!/usr/bin/env bash
# Prepare .github/workflows/ for local compilation.
#
# The gh-aw compiler processes .md files in .github/workflows/. This script
# copies trigger .yml files from gh-agent-workflows/ into .github/workflows/.
#
# Workflow .md files and fragments (gh-aw-fragments/) live directly in
# .github/workflows/ (canonical location).
#
# Usage:
#   ./scripts/dogfood.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# Workflows that are not dogfooded in this repository.
EXCLUDED_WORKFLOWS=(
  "estc-actions-resource-not-accessible-detector"
  "estc-docs-patrol-external"
  "estc-newbie-contributor-patrol-external"
  "flaky-test-investigator"
  "issue-fixer"
  "mention-in-issue-no-sandbox"
  "mention-in-pr-no-sandbox"
  "performance-profiler"
  "pr-review-fork"
  "release-update"
  "scheduled-audit"
  "scheduled-fix"
)

echo "Syncing workflow files..."

# Copy trigger example.yml files from gh-agent-workflows/*/ → .github/workflows/trigger-*
# Rewrite remote uses: references to local paths for dogfooding.
for f in gh-agent-workflows/*/example.yml; do
  [ -e "$f" ] || continue
  dir=$(basename "$(dirname "$f")")
  # Skip excluded workflows.
  skip=false
  for excluded in "${EXCLUDED_WORKFLOWS[@]}"; do
    [[ "$dir" == "$excluded" ]] && skip=true && break
  done
  if [[ "$skip" == "true" ]]; then
    rm -f ".github/workflows/trigger-$dir.yml"
    echo "  ✗ gh-agent-workflows/$dir/example.yml (excluded — manual sync required)"
    continue
  fi
  target=".github/workflows/trigger-$dir.yml"
  {
    echo "# This file is auto-generated by scripts/dogfood.sh. Do not edit directly."
    echo "# Edit gh-agent-workflows/$dir/example.yml and run 'make compile' to regenerate."
    sed 's|uses: elastic/ai-github-actions/\(.*\)@v0|uses: ./\1|; s|^name: |name: Trigger |' "$f"
  } > "$target"

  # Inject dogfood-with.yml overrides into the generated trigger.
  overrides="gh-agent-workflows/$dir/dogfood-with.yml"
  if [[ -f "$overrides" ]]; then
    awk -v of="$overrides" '
      /^    with:/ { in_with=1; next }
      in_with && /^    [a-z]/ { in_with=0 }
      in_with { next }
      /^    secrets:/ {
        print "    with:"
        while ((getline line < of) > 0) {
          print "      " line
        }
        close(of)
      }
      { print }
    ' "$target" > "$target.tmp" && mv "$target.tmp" "$target"
    echo "  ✓ gh-agent-workflows/$dir/example.yml → $target (with dogfood overrides)"
  else
    echo "  ✓ gh-agent-workflows/$dir/example.yml → $target"
  fi
done

echo "✓ Sync complete"
