#!/usr/bin/env bash
# Prepare .github/workflows/ for local compilation.
#
# The gh-aw compiler processes .md files in .github/workflows/. This script
# copies trigger .yml files from gh-agent-workflows/ into .github/workflows/.
#
# Workflow .md files and fragments (gh-aw-fragments/) live directly in
# .github/workflows/ (canonical location).
#
# Usage:
#   ./scripts/dogfood.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# Workflows that are not dogfooded in this repository.
EXCLUDED_WORKFLOWS=(
  "bug-exterminator"
  "code-duplication-fixer"
  "code-simplifier"
  "estc-actions-resource-not-accessible-detector"
  "estc-docs-patrol-external"
  "estc-newbie-contributor-patrol-external"
  "flaky-test-investigator"
  "issue-fixer"
  "mention-in-issue-no-sandbox"
  "mention-in-pr-no-sandbox"
  "newbie-contributor-fixer"
  "performance-profiler"
  "pr-actions-fixer"
  "pr-review-addresser"
  "pr-review-fork"
  "release-update"
  "scheduled-audit"
  "scheduled-fix"
  "small-problem-fixer"
  "test-improver"
  "text-beautifier"
)

# Workflows that should auto-chain issue -> remediation PR in generated dogfood triggers.
# These entries refer to gh-agent-workflows/<name>/example.yml directories.
REMEDIATION_WORKFLOWS=(
  "docs-patrol"
  "framework-best-practices"
  "text-auditor"
)

echo "Syncing workflow files..."

# Copy trigger example.yml files from gh-agent-workflows/*/ → .github/workflows/trigger-*
# Rewrite remote uses: references to local paths for dogfooding.
for f in gh-agent-workflows/*/example.yml; do
  [ -e "$f" ] || continue
  dir=$(basename "$(dirname "$f")")
  # Skip excluded workflows.
  skip=false
  for excluded in "${EXCLUDED_WORKFLOWS[@]}"; do
    [[ "$dir" == "$excluded" ]] && skip=true && break
  done
  if [[ "$skip" == "true" ]]; then
    rm -f ".github/workflows/trigger-$dir.yml"
    echo "  ✗ gh-agent-workflows/$dir/example.yml (excluded — manual sync required)"
    continue
  fi
  target=".github/workflows/trigger-$dir.yml"
  {
    echo "# This file is auto-generated by scripts/dogfood.sh. Do not edit directly."
    echo "# Edit gh-agent-workflows/$dir/example.yml and run 'make compile' to regenerate."
    sed 's|uses: elastic/ai-github-actions/\(.*\)@v0|uses: ./\1|; s|^name: |name: Trigger |' "$f"
  } > "$target"

  # Inject dogfood-with.yml overrides into the generated trigger.
  overrides="gh-agent-workflows/$dir/dogfood-with.yml"
  if [[ -f "$overrides" ]]; then
    awk -v of="$overrides" '
      /^  [^ ]+:/ { current_job=$0; sub(/^  /, "", current_job); sub(/:$/, "", current_job) }
      current_job=="run" && /^    with:/ { in_with=1; next }
      in_with && /^    [a-z]/ { in_with=0 }
      in_with { next }
      current_job=="run" && /^    secrets:/ {
        print "    with:"
        while ((getline line < of) > 0) {
          print "      " line
        }
        close(of)
      }
      { print }
    ' "$target" > "$target.tmp" && mv "$target.tmp" "$target"
    echo "  ✓ gh-agent-workflows/$dir/example.yml → $target (with dogfood overrides)"
  else
    echo "  ✓ gh-agent-workflows/$dir/example.yml → $target"
  fi

  # Inject EXTRA_COMMIT_GITHUB_TOKEN secret for lock workflows that accept it.
  # This token enables commits made by workflows to trigger downstream CI runs.
  lockfile=".github/workflows/gh-aw-${dir}.lock.yml"
  if [[ -f "$lockfile" ]] && grep -q "EXTRA_COMMIT_GITHUB_TOKEN" "$lockfile"; then
    sed '/COPILOT_GITHUB_TOKEN:/a\
      EXTRA_COMMIT_GITHUB_TOKEN: ${{ secrets.EXTRA_COMMIT_GITHUB_TOKEN }}' "$target" > "$target.tmp" && mv "$target.tmp" "$target"
    echo "    + injected EXTRA_COMMIT_GITHUB_TOKEN secret"
  fi

  # Append automatic issue -> PR remediation chain for selected workflows.
  add_remediation=false
  for remediation in "${REMEDIATION_WORKFLOWS[@]}"; do
    [[ "$dir" == "$remediation" ]] && add_remediation=true && break
  done
  if [[ "$add_remediation" == "true" ]]; then
    # Ensure permissions allow downstream PR creation job and artifact reads.
    awk '
      BEGIN { in_permissions=0; have_actions=0 }
      /^permissions:/ { in_permissions=1; print; next }
      in_permissions {
        if (/^jobs:/) {
          if (!have_actions) print "  actions: read"
          in_permissions=0
          print
          next
        }
        if ($0 ~ /^  contents: /) sub(/read$/, "write")
        if ($0 ~ /^  pull-requests: /) sub(/read$/, "write")
        if ($0 ~ /^  actions: /) {
          if ($0 ~ /none$/) sub(/none$/, "read")
          have_actions=1
        }
        print
        next
      }
      { print }
    ' "$target" > "$target.tmp" && mv "$target.tmp" "$target"

    cat >> "$target" <<'EOF'

  resolve_created_issue:
    needs: run
    runs-on: ubuntu-slim
    outputs:
      created_issue_number: ${{ steps.resolve.outputs.created_issue_number }}
    steps:
      - name: Download safe output items
        uses: actions/download-artifact@v4
        with:
          name: safe-output-items
          path: /tmp/safe-output-items
      - name: Resolve created issue number
        id: resolve
        run: |
          number="$(grep -m1 -oE '"number":[[:space:]]*[0-9]+' /tmp/safe-output-items/safe-output-items.jsonl | tr -cd '0-9' || true)"
          echo "created_issue_number=$number" >> "$GITHUB_OUTPUT"

  create_pr_from_issue:
    needs: resolve_created_issue
    if: ${{ needs.resolve_created_issue.outputs.created_issue_number != '' }}
    uses: ./.github/workflows/gh-aw-create-pr-from-issue.lock.yml
    with:
      target-issue-number: ${{ needs.resolve_created_issue.outputs.created_issue_number }}
      additional-instructions: "Create a focused pull request that resolves this issue."
    secrets:
      COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
      EXTRA_COMMIT_GITHUB_TOKEN: ${{ secrets.EXTRA_COMMIT_GITHUB_TOKEN }}
EOF
    echo "    + appended remediation chain jobs"
  fi
done

echo "✓ Sync complete"
