#!/usr/bin/env python3
"""Fix reaction token references in compiled lock files.

The gh-aw compiler generates reaction steps with github-token: ${{ secrets.GITHUB_TOKEN }},
but this should use the automatic github.token instead for proper permissions.
This script post-processes all .lock.yml files to fix this issue.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


def main() -> int:
    """Fix reaction token references in all .lock.yml files."""
    # Pattern to match the reaction step's github-token line
    # We need to be specific to only match the reaction steps, not other uses of github-token
    token_pattern = re.compile(
        r"^(\s+github-token:\s+\$\{\{\s+)secrets\.GITHUB_TOKEN(\s+\}\})$"
    )
    
    updated_files = 0
    updated_lines = 0
    
    # Find all .lock.yml files in .github/workflows
    workflows_dir = Path(".github/workflows")
    if not workflows_dir.exists():
        print("Error: .github/workflows directory not found", file=sys.stderr)
        return 1
    
    for path in workflows_dir.glob("*.lock.yml"):
        original = path.read_text(encoding="utf-8")
        lines = original.splitlines(keepends=True)
        new_lines: list[str] = []
        file_changed = False
        in_reaction_step = False
        has_gh_aw_reaction = False
        
        for i, line in enumerate(lines):
            # More robust detection: Look for GH_AW_REACTION environment variable
            # This is set by the gh-aw compiler for reaction steps
            if "GH_AW_REACTION:" in line:
                has_gh_aw_reaction = True
            
            # Detect if we're in a reaction step by looking for the step name
            # These strings are generated by the gh-aw compiler v0.79.3
            if "Add eyes reaction for immediate feedback" in line or "Add reaction for immediate feedback" in line:
                in_reaction_step = True
            # Exit reaction step when we hit the next step (starts with "- name:")
            elif in_reaction_step and line.strip().startswith("- name:"):
                in_reaction_step = False
                has_gh_aw_reaction = False
            
            # Only replace github-token if we're in a reaction step and have seen GH_AW_REACTION
            if in_reaction_step and has_gh_aw_reaction:
                # Strip line ending for pattern matching, but preserve it
                line_stripped = line.rstrip("\r\n")
                match = token_pattern.match(line_stripped)
                if match:
                    prefix, suffix = match.groups()
                    # Preserve original line ending (could be \n, \r\n, or empty)
                    line_ending = line[len(line_stripped):]
                    # Replace secrets.GITHUB_TOKEN with github.token
                    new_line = f"{prefix}github.token{suffix}{line_ending}"
                    if new_line != line:
                        file_changed = True
                        updated_lines += 1
                        print(f"  Fixed token reference in {path.name}")
                    new_lines.append(new_line)
                    continue
            
            new_lines.append(line)
        
        if file_changed:
            path.write_text("".join(new_lines), encoding="utf-8")
            updated_files += 1
    
    print(f"\n✓ Updated {updated_lines} token reference(s) in {updated_files} workflow file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
