#
# Composite Action for analyzing Buildkite CI build failures with Claude
#
# Usage:
#   - uses: elastic/ai-github-actions/workflows/build-failure-buildkite/rwx@v0
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#       buildkite-api-token: ${{ secrets.BUILDKITE_API_TOKEN }}
#
name: "Claude Buildkite Build Failure Analysis"
description: "Analyze Buildkite CI build failures and suggest fixes using Claude"

branding:
  icon: "alert-triangle"
  color: "red"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  buildkite-api-token:
    description: "Buildkite API token for accessing build logs"
    required: true

  buildkite-org:
    description: "Buildkite organization slug"
    required: false
    default: "elastic"

  buildkite-pipeline:
    description: "Buildkite pipeline slug (optional - auto-discovered from repo name if not provided)"
    required: false
    default: ""

  buildkite-build-number:
    description: "Buildkite build number (optional - auto-discovered from commit SHA if not provided)"
    required: false
    default: ""

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-opus-4-5-20251101"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    default: "Edit,MultiEdit,Glob,Grep,LS,Read,Write,WebSearch,WebFetch,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(*),mcp__agents-md-generator__generate_agents_md,mcp__public-code-search__search_code,mcp__buildkite"

  extra-allowed-tools:
    description: "Additional comma-separated list of allowed tools (concatenated with allowed-tools)"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "Additional MCP server configuration JSON (merged with defaults)"
    required: false
    default: ""

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Build MCP Server Configuration
      id: mcp-config
      shell: bash
      env:
        BUILDKITE_API_TOKEN: ${{ inputs.buildkite-api-token }}
        ADDITIONAL_MCP: ${{ inputs.mcp-servers }}
      run: |
        # Build MCP config as inline JSON (don't write secrets to disk)
        # See: https://github.com/anthropics/claude-code-action/issues/754
        BASE_CONFIG=$(jq -n \
          --arg token "$BUILDKITE_API_TOKEN" \
          '{
            "mcpServers": {
              "agents-md-generator": {
                "type": "http",
                "url": "https://agents-md-generator.fastmcp.app/mcp"
              },
              "public-code-search": {
                "type": "http",
                "url": "https://public-code-search.fastmcp.app/mcp"
              },
              "buildkite": {
                "type": "http",
                "url": "https://mcp.buildkite.com/mcp/readonly",
                "headers": {
                  "Authorization": ("Bearer " + $token)
                }
              }
            }
          }')
        
        # Merge additional MCP servers if provided
        if [ -n "$ADDITIONAL_MCP" ]; then
          FINAL_CONFIG=$(echo "$BASE_CONFIG" | jq --argjson additional "$ADDITIONAL_MCP" '. * $additional')
        else
          FINAL_CONFIG="$BASE_CONFIG"
        fi
        
        # Output as compact JSON for claude_args
        echo "mcp_json=$(echo "$FINAL_CONFIG" | jq -c .)" >> "$GITHUB_OUTPUT"

    - name: Run Claude for Buildkite Build Failure Analysis
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      uses: elastic/ai-github-claude-code-action@working-forks
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          <context>
          Repository: ${{ github.repository }}
          Event: ${{ github.event_name }}
          Branch: ${{ github.event.workflow_run.head_branch || github.head_ref || github.ref_name }}
          Commit SHA: ${{ github.event.workflow_run.head_sha || github.sha }}
          ${{ github.event.workflow_run.name && format('Failed Workflow: {0}', github.event.workflow_run.name) || '' }}
          ${{ github.event.workflow_run.id && format('Workflow Run ID: {0}', github.event.workflow_run.id) || '' }}
          ${{ github.event.workflow_run.html_url && format('Workflow URL: {0}', github.event.workflow_run.html_url) || '' }}
          </context>

          <buildkite_config>
          Organization: ${{ inputs.buildkite-org }}
          ${{ inputs.buildkite-pipeline != '' && format('Pipeline: {0} (provided)', inputs.buildkite-pipeline) || 'Pipeline: Auto-discover from repo name' }}
          ${{ inputs.buildkite-build-number != '' && format('Build Number: {0} (provided)', inputs.buildkite-build-number) || 'Build Number: Auto-discover from commit SHA' }}
          </buildkite_config>

          <task>
          A Buildkite CI build has failed. Analyze the failure, identify the root cause, and provide actionable fix recommendations via a GitHub comment.
          You can suggest code fixes. Check the `<allowed_tools>` section to see if you can run tests to verify your recommendations.
          </task>

          <constraints>
          This workflow allows code suggestions, but feedback is provided via GitHub comments.
          
          You CAN: Read/analyze code, suggest code fixes, write/modify files locally to verify your recommendations work, run tests if Bash commands are available (check `<allowed_tools>` section)
          You CANNOT: Create branches, commit code, push changes
          
          **Important**: You can make local code changes to verify your recommendations work, but you cannot commit or push those changes.
          Your analysis and recommendations are provided via a GitHub comment. Local changes are for verification/testing only.
          </constraints>

          <allowed_tools>
          You have access to the following tools (comma-separated list):
          
          ${{ inputs.allowed-tools }}
          ${{ inputs.extra-allowed-tools }}
          
          You can only use tools that are explicitly listed above. For Bash commands, the pattern `Bash(command:*)` means you can run that command with any arguments. If a command is not listed, it is not available.
          </allowed_tools>

          <getting_started>
          Use `mcp__agents-md-generator__generate_agents_md` to get repository context before investigating.
          </getting_started>

          <investigation_tools>
          - `mcp__buildkite`: Query build information, job logs, and annotations
          - `mcp__public-code-search__search_code`: Search code in OTHER repositories (use `Grep`/`Read` for this repo)
          - `WebSearch`: Search for error messages, build failures, or solutions
          - `WebFetch`: Fetch documentation or API references
          </investigation_tools>

          <failure_categories>
          Common failure types to identify:
          - Code bug: Logic error, syntax error, type mismatch
          - Test failure: Assertion failed, test timeout, flaky test
          - Dependency issue: Missing package, version conflict, network failure
          - Infrastructure: Resource exhaustion, service unavailability, timeout
          - Configuration: Invalid settings, missing secrets, incorrect paths
          </failure_categories>

          <buildkite_workflow>
          Step 1 - Find the pipeline:
          ${{ inputs.buildkite-pipeline != '' && format('Use provided pipeline: {0}', inputs.buildkite-pipeline) || format('Use `list_pipelines` for organization `{0}` to find pipelines matching repository `{1}`', inputs.buildkite-org, github.repository) }}

          Step 2 - Find the failed build:
          ${{ inputs.buildkite-build-number != '' && format('Use provided build number: {0}', inputs.buildkite-build-number) || format('Use `list_builds` to find builds matching commit SHA `{0}` or branch `{1}`', github.event.workflow_run.head_sha || github.sha, github.event.workflow_run.head_branch || github.head_ref || github.ref_name) }}

          Step 3 - Get build details:
          Use `get_build` with organization `${{ inputs.buildkite-org }}`, pipeline, and build number.

          Step 4 - Analyze failed jobs:
          For each failed job:
          - Use `get_job_logs` to retrieve full logs
          - Use `search_logs` with patterns: `error|Error|ERROR`, `failed|Failed|FAILED`, `panic|exception`
          - Use `tail_logs` to see the last 100 lines

          Step 5 - Check annotations:
          Use `list_annotations` for build annotations with errors/warnings.
          </buildkite_workflow>

          <analysis_process>
          1. Identify which Buildkite jobs failed
          2. Extract specific error messages and stack traces
          3. Determine root cause (code bug, test failure, dependency, infrastructure, config)
          4. Analyze relevant source files in the repository
          5. Provide specific, actionable fix recommendations
          </analysis_process>

          <response_format>
          Structure your response as:

          **Build**: [Link to Buildkite build]

          **What failed**: Which job(s) failed

          **Error**: Key error message(s)

          **Root cause**: What caused the failure

          **Recommended fix**: Specific steps to resolve

          **Code changes** (if applicable):
          ```suggestion
          corrected code here
          ```

          Be concise and actionable. Focus on the specific fix needed.
          </response_format>

          <response_footer>
          Always end your comment with a new line, three dashes, and the footer message:
          <exact_content>

          ---
          [Why is Claude responding?](https://ela.st/github-ai-tools) | Type `@claude` to interact further

          Give us feedback! React with 🚀 if perfect, 👍 if helpful, 👎 if not.
          </exact_content>
          </response_footer>

          <additional_instructions>
          ${{ inputs.additional-instructions }}
          </additional_instructions>
        claude_args: |
          ${{ format('--allowedTools {0}{1}', inputs.allowed-tools, inputs.extra-allowed-tools != '' && format(',{0}', inputs.extra-allowed-tools) || '') }}
          --mcp-config '${{ steps.mcp-config.outputs.mcp_json }}'
          --model ${{ inputs.model }}
