# Composite Action for running Claude Code Action
#
# This action wraps the Anthropic Claude Code Action with MCP server configuration.
#
# Usage:
#   - uses: elastic/ai-github-actions/base@v0
#     with:
#       prompt: "Your prompt here"
#       claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude Code Action"
description: "Run Claude Code with MCP servers"
author: "Elastic"

branding:
  icon: "cpu"
  color: "orange"

inputs:
  prompt:
    description: "Prompt to pass to Claude"
    required: true

  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude (e.g., Edit,Write,Bash(npm test))"
    required: false
    default: ""

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-opus-4-5-20251101"

  allowed-bots:
    description: "Comma-separated list of allowed bot usernames, or '*' to allow all bots"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress"
    required: false
    default: "true"

  claude-args:
    description: "Additional arguments to pass to Claude"
    required: false
    default: ""

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: ''

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Run Claude Code
      id: claude
      uses: elastic/ai-github-claude-code-action@working-forks
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        prompt: ${{ inputs.prompt }}
        track_progress: ${{ inputs.track-progress }}
        allowed_bots: ${{ inputs.allowed-bots }}
        claude_args: |
          ${{ inputs.allowed-tools != '' && format('--allowedTools {0}', inputs.allowed-tools) || '' }}
          ${{ inputs.mcp-servers != '' && format('--mcp-config ''{0}''', inputs.mcp-servers) || '' }}
          --model ${{ inputs.model }}
          ${{ inputs.claude-args }}
