#
# Composite Action for analyzing GitHub Actions build failures with Claude
#
# Usage:
#   - uses: elastic/ai-github-actions/workflows/build-failure-github-actions/rwx@v1
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude GitHub Actions Build Failure Analysis"
description: "Analyze GitHub Actions workflow failures and suggest fixes using Claude"

branding:
  icon: "alert-triangle"
  color: "red"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-opus-4-5-20251101"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    default: "Edit,MultiEdit,Glob,Grep,LS,Read,Write,WebSearch,WebFetch,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(*),mcp__agents-md-generator__generate_agents_md,mcp__public-code-search__search_code"

  extra-allowed-tools:
    description: "Additional comma-separated list of allowed tools (concatenated with allowed-tools)"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: '{"mcpServers":{"agents-md-generator":{"type":"http","url":"https://agents-md-generator.fastmcp.app/mcp"},"public-code-search":{"type":"http","url":"https://public-code-search.fastmcp.app/mcp"}}}'

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Run Claude for GitHub Actions Build Failure Analysis
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          <context>
          Repository: ${{ github.repository }}
          Event: ${{ github.event_name }}
          Branch: ${{ github.event.workflow_run.head_branch || github.head_ref || github.ref_name }}
          Commit SHA: ${{ github.event.workflow_run.head_sha || github.sha }}
          ${{ github.event.workflow_run.name && format('Failed Workflow: {0}', github.event.workflow_run.name) || '' }}
          ${{ github.event.workflow_run.id && format('Workflow Run ID: {0}', github.event.workflow_run.id) || '' }}
          ${{ github.event.workflow_run.html_url && format('Workflow URL: {0}', github.event.workflow_run.html_url) || '' }}
          </context>

          <task>
          A GitHub Actions workflow has failed. Analyze the failure, identify the root cause, and provide actionable fix recommendations via a GitHub comment.
          You can suggest code fixes. Check the `<allowed_tools>` section to see if you can run tests to verify your recommendations.
          </task>

          <constraints>
          This workflow allows code suggestions, but feedback is provided via GitHub comments.
          
          You CAN: Read/analyze code, suggest code fixes, write/modify files locally to verify your recommendations work, run tests if Bash commands are available (check `<allowed_tools>` section)
          You CANNOT: Create branches, commit code, push changes
          
          **Important**: You can make local code changes to verify your recommendations work, but you cannot commit or push those changes.
          Your analysis and recommendations are provided via a GitHub comment. Local changes are for verification/testing only.
          </constraints>

          <allowed_tools>
          You have access to the following tools (comma-separated list):
          
          ${{ inputs.allowed-tools }}
          ${{ inputs.extra-allowed-tools }}
          
          You can only use tools that are explicitly listed above. For Bash commands, the pattern `Bash(command:*)` means you can run that command with any arguments. If a command is not listed, it is not available.
          </allowed_tools>

          <getting_started>
          Use `mcp__agents-md-generator__generate_agents_md` to get repository context before investigating.
          </getting_started>

          <investigation_tools>
          - `mcp__github_ci__get_ci_status`: Get CI workflow status for this repository
          - `mcp__github_ci__get_workflow_run_details`: Get detailed workflow run information
          - `mcp__github_ci__download_job_log`: Download logs from failed jobs
          - `mcp__public-code-search__search_code`: Search code in OTHER repositories (use `Grep`/`Read` for this repo)
          - `WebSearch`: Search for error messages, build failures, or solutions
          - `WebFetch`: Fetch documentation or API references
          </investigation_tools>

          <failure_categories>
          Common failure types to identify:
          - Code bug: Logic error, syntax error, type mismatch
          - Test failure: Assertion failed, test timeout, flaky test
          - Dependency issue: Missing package, version conflict, network failure
          - Infrastructure: Resource exhaustion, service unavailability, timeout
          - Workflow config: Invalid YAML, missing secrets, incorrect paths, permission issues
          </failure_categories>

          <github_actions_workflow>
          Step 1 - Get workflow run details:
          Use `mcp__github_ci__get_workflow_run_details` with workflow run ID to see:
          - Which jobs failed
          - Status of each job
          - Links to job logs

          Step 2 - Download failed job logs:
          Use `mcp__github_ci__download_job_log` for each failed job. Look for:
          - Error messages
          - Stack traces
          - Test failures
          - Build errors

          Step 3 - Analyze workflow file:
          Review `.github/workflows/*.yml` to understand:
          - What the workflow is trying to do
          - Which steps are failing
          - Dependencies between jobs
          - Environment setup requirements
          </github_actions_workflow>

          <analysis_process>
          1. Identify which jobs/steps failed
          2. Extract specific error messages and stack traces
          3. Determine root cause (code bug, test failure, dependency, infrastructure, workflow config)
          4. Analyze relevant source files in the repository
          5. Review workflow YAML for configuration issues
          6. Provide specific, actionable fix recommendations
          </analysis_process>

          <response_format>
          Structure your response as:

          **Workflow**: [Link to failed workflow run]

          **What failed**: Which job(s)/step(s) failed

          **Error**: Key error message(s)

          **Root cause**: What caused the failure

          **Recommended fix**: Specific steps to resolve

          **Code changes** (if applicable):
          ```suggestion
          corrected code here
          ```

          **Workflow changes** (if applicable):
          ```yaml
          corrected workflow YAML here
          ```

          Be concise and actionable. Focus on the specific fix needed.
          </response_format>

          <response_footer>
          Always end your comment with a new line, three dashes, and the footer message:
          <exact_content>

          ---
          [Why is Claude responding?](https://ela.st/github-ai-tools) | Type `@claude` to interact further

          Give us feedback! React with 🚀 if perfect, 👍 if helpful, 👎 if not.
          </exact_content>
          </response_footer>

          <additional_instructions>
          ${{ inputs.additional-instructions }}
          </additional_instructions>
        claude_args: |
          ${{ format('--allowedTools {0}{1}', inputs.allowed-tools, inputs.extra-allowed-tools != '' && format(',{0}', inputs.extra-allowed-tools) || '') }}
          --mcp-config '${{ inputs.mcp-servers }}'
          --model ${{ inputs.model }}
