# Example workflow for GitHub Actions build failure analysis
# Copy this to your repo's .github/workflows/ directory

name: Build Failure Analysis

on:
  workflow_run:
    workflows: ["CI", "Build", "Test"]  # Names of workflows to monitor
    types: [completed]

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.id }}
  cancel-in-progress: false

jobs:
  analyze:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Place environment setup commands here (e.g., install dependencies, configure tools)

      - name: Run Claude Build Failure Analysis
        uses: elastic/ai-github-actions/workflows/build-failure-github-actions/rwx@v1
        with:
          claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
          github-token: ${{ github.token }}
