#
# Composite Action for AI Agent Feedback Summary
#
# Collects reactions on AI agent comments and creates a GitHub issue
# with a summary table and analysis of recent interactions.
#
# Usage:
#   - uses: elastic/ai-github-actions/workflows/feedback-summary/ro@v1
#     with:
#       github-token: ${{ github.token }}
#
name: "AI Agent Feedback Summary"
description: "Collect and analyze feedback on AI agent interactions"

branding:
  icon: "bar-chart-2"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token for API access and creating issues"
    required: true

  claude-oauth-token:
    description: "Claude OAuth token for AI analysis (optional - skip analysis if not provided)"
    required: false

  days:
    description: "Number of days to look back for feedback"
    required: false
    default: "7"

  bot-pattern:
    description: "Regex pattern to match bot usernames (e.g., 'claude|github-actions\\[bot\\]')"
    required: false
    default: "claude|github-actions\\[bot\\]|copilot\\[bot\\]"

  model:
    description: "Model to use for Claude analysis"
    required: false
    default: "claude-opus-4-5-20251101"

  issue-labels:
    description: "Comma-separated labels to add to the summary issue"
    required: false
    default: "ai-feedback,automated"

  create-issue:
    description: "Whether to create a GitHub issue with the summary"
    required: false
    default: "true"

outputs:
  feedback-json:
    description: "JSON data with collected feedback"
    value: ${{ steps.collect.outputs.feedback_json }}
  
  issue-url:
    description: "URL of the created issue (if create-issue is true)"
    value: ${{ steps.create-issue.outputs.issue_url }}

runs:
  using: "composite"
  steps:
    - name: Collect feedback data
      id: collect
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        FEEDBACK_REPO: ${{ github.repository }}
        FEEDBACK_BOT_PATTERN: ${{ inputs.bot-pattern }}
        FEEDBACK_DAYS: ${{ inputs.days }}
      run: |
        chmod +x "${{ github.action_path }}/scripts/collect-feedback.sh"
        FEEDBACK=$("${{ github.action_path }}/scripts/collect-feedback.sh")
        
        # Save to file for later steps
        echo "$FEEDBACK" > "${{ runner.temp }}/feedback-data.json"
        
        # Output summary
        TOTAL=$(echo "$FEEDBACK" | jq '.summary.total_interactions')
        POSITIVE=$(echo "$FEEDBACK" | jq '.summary.positive_reactions')
        NEGATIVE=$(echo "$FEEDBACK" | jq '.summary.negative_reactions')
        
        echo "Collected feedback: ${TOTAL} interactions (${POSITIVE} positive, ${NEGATIVE} negative)"
        
        # Set output
        echo "feedback_json<<EOF" >> $GITHUB_OUTPUT
        echo "$FEEDBACK" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Generate summary report
      id: report
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/generate-report.sh"
        "${{ github.action_path }}/scripts/generate-report.sh" "${{ runner.temp }}/feedback-data.json" "${{ runner.temp }}/feedback-report.md"

    - name: Run Claude analysis (if token provided)
      id: analysis
      if: ${{ inputs.claude-oauth-token != '' }}
      uses: elastic/ai-github-claude-code-action@working-forks
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        prompt: |
          Analyze the AI agent feedback data and provide insights.
          
          <task>
          1. Read the feedback data from the feedback JSON file
          2. Read the current report from the feedback report markdown file
          
          3. Analyze the feedback patterns:
             - What types of interactions get the best reactions?
             - What patterns appear in negative feedback?
             - Are there specific PRs/issues with recurring problems?
          
          4. Identify actionable improvements:
             - What could the AI agent do better?
             - Are there common misunderstandings or errors?
             - What prompting or configuration changes might help?
          
          5. Append your analysis to the feedback report markdown file under a new section:
             ### AI Analysis
             
             Keep the analysis concise (3-5 key insights) and actionable.
             If there's not enough data or no clear patterns, say so briefly.
          </task>
        # Note: This workflow intentionally hardcodes allowed tools (Read,Grep only)
        # rather than using dynamic inputs. It's a specialized analysis workflow that
        # only needs to read files - no customization is expected or needed.
        claude_args: |
          --allowedTools Read,Grep
          --model ${{ inputs.model }}

    - name: Create GitHub issue
      id: create-issue
      if: ${{ inputs.create-issue == 'true' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        FEEDBACK=$(cat "${{ runner.temp }}/feedback-data.json")
        TOTAL=$(echo "$FEEDBACK" | jq '.summary.total_interactions')
        
        # Skip creating issue if no interactions found
        if [ "$TOTAL" -eq 0 ]; then
          echo "No AI agent interactions found in the specified period. Skipping issue creation."
          echo "issue_url=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        TITLE="AI Agent Feedback Summary - $(date +%Y-%m-%d)"
        LABELS="${{ inputs.issue-labels }}"
        
        # Read the report
        BODY=$(cat "${{ runner.temp }}/feedback-report.md")
        
        # Create the issue
        ISSUE_URL=$(gh issue create \
          --repo "${{ github.repository }}" \
          --title "$TITLE" \
          --body "$BODY" \
          --label "$LABELS" \
          2>&1) || {
          echo "Failed to create issue"
          exit 1
        }
        
        echo "Created issue: $ISSUE_URL"
        echo "issue_url=$ISSUE_URL" >> $GITHUB_OUTPUT
