# Composite Action for PR review with Claude
#
# Usage:
#   - uses: your-org/ai-github-actions/workflows/pr-review@v1
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude PR Review"
description: "Review pull requests using Claude"

branding:
  icon: "git-pull-request"
  color: "purple"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-sonnet-4-20250514"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: '{"mcpServers":{"agents-md-generator":{"type":"http","url":"https://agents-md-generator.fastmcp.app/mcp"},"public-code-search":{"type":"http","url":"https://public-code-search.fastmcp.app/mcp"}}}'

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Run Claude for PR Review
      id: claude
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          ## GitHub Context
          - Repository: ${{ github.repository }}
          - PR Number: #${{ github.event.pull_request.number }}
          - PR Title: ${{ github.event.pull_request.title }}
          - PR Author: ${{ github.event.pull_request.user.login }}
          - Base Branch: ${{ github.event.pull_request.base.ref }}
          - Head Branch: ${{ github.event.pull_request.head.ref }}
          - PR Body:
          ```
          ${{ github.event.pull_request.body }}
          ```

          ## Instructions
          Please review this pull request:

          1. **Understand the changes** - Review the PR description and all modified files
          2. **Code quality** - Check for:
             - Code style and consistency
             - Potential bugs or edge cases
             - Error handling
             - Performance considerations
          3. **Testing** - Verify adequate test coverage for the changes
          4. **Documentation** - Check if documentation needs updating
          5. **Security** - Look for any security concerns
          6. **Provide feedback** - Post a review comment that:
             - Summarizes what the PR does
             - Highlights any concerns or suggestions
             - Notes positive aspects of the changes
             - Provides specific, actionable feedback

          Be constructive and helpful. Focus on significant issues rather than nitpicks.

          ## Response Footer
          Always end your comment with this footer (using markdown):
          ```
          ---
          *Comment by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type `@claude` to interact further
          ```

          ${{ inputs.additional-instructions }}
        claude_args: |
          ${{ inputs.allowed-tools != '' && format('--allowedTools {0}', inputs.allowed-tools) || '' }}
          --mcp-config '${{ inputs.mcp-servers }}'
          --model ${{ inputs.model }}
