#
# Composite Action for PR review with Claude
#
# Usage:
#   - uses: your-org/ai-github-actions/workflows/pr-review@v1
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude PR Review"
description: "Review pull requests using Claude"

branding:
  icon: "git-pull-request"
  color: "purple"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-sonnet-4-20250514"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    # Note: Using ${{ github.action_path }} for the PR review scripts
    default: "Edit,MultiEdit,Glob,Grep,LS,Read,Write,WebSearch,WebFetch,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(git add:*),Bash(git commit:*),Bash(git push:*),Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(git rm:*),Bash,mcp__agents-md-generator__generate_agents_md,mcp__agents-md-generator,mcp__public-code-search__search_code,Bash(${{ github.action_path }}/scripts/pr-comment.sh:*),Bash(${{ github.action_path }}/scripts/pr-review.sh:*),Bash(${{ github.action_path }}/scripts/pr-diff.sh:*)"

  extra-allowed-tools:
    description: "Additional comma-separated list of allowed tools (concatenated with allowed-tools)"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: '{"mcpServers":{"agents-md-generator":{"type":"http","url":"https://agents-md-generator.fastmcp.app/mcp"},"public-code-search":{"type":"http","url":"https://public-code-search.fastmcp.app/mcp"}}}'

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Fetch base branch for comparison
      shell: bash
      run: |
        BASE_REF="${{ github.event.pull_request.base.ref }}"
        echo "Fetching base branch: ${BASE_REF}"
        git fetch origin "${BASE_REF}:${BASE_REF}" || echo "Warning: Could not fetch base branch ${BASE_REF}"
    
    - name: Run Claude for PR Review
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_REVIEW_REPO: ${{ github.repository }}
        PR_REVIEW_PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_REVIEW_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_REVIEW_BASE_REF: ${{ github.event.pull_request.base.ref }}
        PR_SCRIPTS: ${{ github.action_path }}/scripts
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          ## GitHub Context
          - Repository: ${{ github.repository }}
          - PR Number: #${{ github.event.pull_request.number }}
          - PR Title: ${{ github.event.pull_request.title }}
          - PR Author: ${{ github.event.pull_request.user.login }}
          - Base Branch: ${{ github.event.pull_request.base.ref }}
          - Head Branch: ${{ github.event.pull_request.head.ref }}
          - PR Body:
          ```
          ${{ github.event.pull_request.body }}
          ```

          ## Instructions
          
          ### Getting Started
          **First, get repository context**: Use the `mcp__agents-md-generator__generate_agents_md` tool to generate a repository summary. This will give you essential context about the codebase structure, technologies used, and project conventions. Call this tool at the start of your investigation.

          **If you encounter any issues using tools** (e.g., tool not found, permission errors, API failures), mention this in your response with a link to the support channel: https://elastic.slack.com/archives/C0AAMNAA89M

          ### Investigation Approach
          **Be extremely thorough in your investigations**. Don't rush to conclusions. Take time to:
          - Understand the full context of the repository
          - Review related code, issues, and PRs
          - Consider edge cases and implications
          - Gather all relevant information before responding

          **Available tools for investigation**:
          - **`mcp__public-code-search__search_code`**: Use this to search for code patterns in OTHER repositories (external libraries, modules, or dependencies). The current repository is cloned locally, so use `Grep` or `Read` for searching within this repo. Use `search_code` for finding similar implementations in other projects or understanding how other repositories handle similar issues.
          - **`WebSearch`**: Use for searching the web for documentation, best practices, or solutions.
          - **`WebFetch`**: Use to fetch and read content from URLs (documentation, API references, etc.).
          - **`git diff`**: The base branch (`${{ github.event.pull_request.base.ref }}`) has been fetched locally. You can use `git diff ${{ github.event.pull_request.base.ref }}` to compare changes, or `git diff ${{ github.event.pull_request.base.ref }} -- <file>` for specific files.

          Review this pull request with a focus on **specific, objective insights** based on codebase context:

          ## Review Process

          1. **Understand the broader context**:
             - Review similar code patterns elsewhere in the codebase for consistency
             - Check how similar features are implemented in other files/modules
             - Understand the change's role in the larger system architecture
             - Identify related code that might be affected or should be updated

          2. **Review code consistency**:
             - Compare coding patterns, naming conventions, and structure with existing code
             - Check if error handling follows established patterns
             - Verify that the code matches the project's style guide and conventions
             - Look for deviations from established patterns that should be aligned

          3. **Check call sites and usage**:
             - Find all places where changed functions/methods are called
             - Verify that call sites are compatible with the changes
             - Check if other code needs updates to work with these changes
             - Identify any breaking changes or migration needs

          4. **Review documentation**:
             - Check if feature documentation exists and is accurate
             - Verify that API documentation reflects the changes
             - Look for inline code comments that need updates
             - Check README files, user guides, and other docs that reference this feature

          5. **Verify test coverage**:
             - Check if tests cover the new/changed functionality
             - Verify tests follow the same patterns as existing tests
             - Look for edge cases that aren't covered
             - Check if integration tests are needed

          6. **Identify specific issues**:
             - Look for bugs, logic errors, or incorrect implementations
             - Check for security vulnerabilities or unsafe patterns
             - Identify performance issues or inefficiencies
             - Find missing error handling or edge case coverage

          ## Feedback Guidelines

          **DO:**
          - Provide specific, actionable feedback on concrete issues
          - Reference exact lines of code and specific problems
          - Compare with existing code patterns in the repository
          - Point out inconsistencies with codebase conventions
          - Identify missing documentation or outdated docs
          - Note call sites that need updates
          - Suggest specific code changes or fixes using GitHub's code suggestion syntax when you can provide a concrete, correct implementation
          - Use code suggestions for fixes that can be directly applied (e.g., bug fixes, error handling improvements, style corrections)

          **DO NOT:**
          - Provide general summaries or explanations of what the PR does
          - Praise or compliment the changes ("good addition", "nice work", etc.)
          - Make broad comments about potential system impacts
          - Question the intentions behind the changes
          - Provide feedback that isn't tied to specific code issues
          - Write general observations without concrete examples

          **Focus on objective, fact-based insights** that help improve code quality, consistency, and correctness.

          ## Submitting Your Review

          You have access to helper scripts for submitting PR reviews. The scripts are available at `$PR_SCRIPTS/`.

          ### View changed files
          ```bash
          $PR_SCRIPTS/pr-diff.sh
          ```
          This shows all files changed in the PR with their addition/deletion counts.

          ### View diff for a specific file
          ```bash
          $PR_SCRIPTS/pr-diff.sh path/to/file.go
          ```

          ### Add inline comment on a specific line
          ```bash
          $PR_SCRIPTS/pr-comment.sh <file> <line-number> <comment>
          ```
          
          **Examples:**
          ```bash
          $PR_SCRIPTS/pr-comment.sh src/main.go 42 "This variable is unused and should be removed"
          $PR_SCRIPTS/pr-comment.sh pkg/utils/helper.go 15 "Missing error handling - this could panic if input is nil"
          ```
          
          **Important notes:**
          - Use the **line number from the new file** (not the diff position)
          - You can only comment on lines that appear in the diff (added, modified, or context lines)
          - Each comment will appear as a separate review comment on the PR

          ### Making Code Suggestions (Commitable Changes)
          
          When you want to suggest specific code changes that can be directly applied by the PR author, use GitHub's code suggestion syntax in your inline comments. This allows the author to click "Commit suggestion" to apply your changes.
          
          **Syntax for code suggestions:**
          ```
          ```suggestion
          suggested code here
          ```
          ```
          
          **For multi-line suggestions (replacing a range of lines):**
          ```
          ```suggestion:start-line:end-line
          suggested code here
          ```
          ```
          
          **Example inline comment with code suggestion:**
          ```bash
          $PR_SCRIPTS/pr-comment.sh src/main.go 42 "This error handling can be improved:

          \`\`\`suggestion
          if err != nil {
              log.Errorf(\"Failed to process: %v\", err)
              return fmt.Errorf(\"processing failed: %w\", err)
          }
          \`\`\`"
          ```
          
          **Best practices for code suggestions:**
          - Use code suggestions when you can provide a concrete, correct implementation
          - Include a brief explanation before the suggestion explaining why the change is needed
          - Ensure the suggested code matches the project's style and conventions
          - For complex changes, consider breaking them into multiple suggestions
          - Test that your suggestions are syntactically correct and follow the codebase patterns
          
          **When to use code suggestions vs. regular comments:**
          - **Use code suggestions**: When you can provide a specific, correct fix (e.g., fixing a bug, improving error handling, correcting syntax)
          - **Use regular comments**: When you need to explain a problem but the solution requires more context or discussion

          ### Submit the final review
          ```bash
          $PR_SCRIPTS/pr-review.sh <APPROVE|REQUEST_CHANGES|COMMENT> <review-body>
          ```
          
          **Examples:**
          ```bash
          # If issues were found:
          $PR_SCRIPTS/pr-review.sh REQUEST_CHANGES "Please address the inline comments above.

          ---
          *Comment by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type \`@claude\` to interact further"

          # If no issues found:
          $PR_SCRIPTS/pr-review.sh APPROVE "LGTM - code follows existing patterns and includes appropriate tests.

          ---
          *Comment by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type \`@claude\` to interact further"

          # If just providing feedback without approving/blocking:
          $PR_SCRIPTS/pr-review.sh COMMENT "Some suggestions for consideration (non-blocking).

          ---
          *Comment by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type \`@claude\` to interact further"
          ```

          ### Review workflow
          1. First, use `$PR_SCRIPTS/pr-diff.sh` to see what files changed
          2. Review the code changes and identify issues
          3. Add inline comments for specific issues using `$PR_SCRIPTS/pr-comment.sh`
          4. Submit the final review using `$PR_SCRIPTS/pr-review.sh` with a summary

          **Always include the footer** in your review summary:
          ```
          ---
          *Comment by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type `@claude` to interact further
          ```

          ${{ inputs.additional-instructions }}
        claude_args: |
          ${{ format('--allowedTools {0}{1}', inputs.allowed-tools, inputs.extra-allowed-tools != '' && format(',{0}', inputs.extra-allowed-tools) || '') }}
          --mcp-config "${{ inputs.mcp-servers }}"
          --model ${{ inputs.model }}
