# Composite Action for PR review with Claude
#
# Usage:
#   - uses: your-org/ai-github-actions/workflows/pr-review@v1
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude PR Review"
description: "Review pull requests using Claude"

branding:
  icon: "git-pull-request"
  color: "purple"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-sonnet-4-20250514"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    default: "Edit,MultiEdit,Glob,Grep,LS,Read,Write,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(git add:*),Bash(git commit:*),Bash(git push:*),Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(git rm:*),Bash(gh pr review:*),Bash(gh pr comment:*),Bash(gh api:*),Bash,mage,build,unitTest,fmt,make,update,llc,mcp__agents-md-generator,mcp__public-code-search"

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: '{"mcpServers":{"agents-md-generator":{"type":"http","url":"https://agents-md-generator.fastmcp.app/mcp"},"public-code-search":{"type":"http","url":"https://public-code-search.fastmcp.app/mcp"}}}'

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Run Claude for PR Review
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          ## GitHub Context
          - Repository: ${{ github.repository }}
          - PR Number: #${{ github.event.pull_request.number }}
          - PR Title: ${{ github.event.pull_request.title }}
          - PR Author: ${{ github.event.pull_request.user.login }}
          - Base Branch: ${{ github.event.pull_request.base.ref }}
          - Head Branch: ${{ github.event.pull_request.head.ref }}
          - PR Body:
          ```
          ${{ github.event.pull_request.body }}
          ```

          ## Instructions
          
          ### Getting Started
          **First, get repository context**: Use the `generate_agents_md` tool from the `agents-md-generator` MCP server to generate a repository summary. This will give you essential context about the codebase structure, technologies used, and project conventions. Call this tool at the start of your investigation.

          ### Investigation Approach
          **Be extremely thorough in your investigations**. Don't rush to conclusions. Take time to:
          - Understand the full context of the repository
          - Review all modified files and related code
          - Check for related issues, PRs, and discussions
          - Consider edge cases, performance, and security implications
          - Gather all relevant information before providing feedback

          Please review this pull request:

          1. **Understand the changes** - Review the PR description and all modified files
          2. **Code quality** - Check for:
             - Code style and consistency
             - Potential bugs or edge cases
             - Error handling
             - Performance considerations
          3. **Testing** - Verify adequate test coverage for the changes
          4. **Documentation** - Check if documentation needs updating
          5. **Security** - Look for any security concerns
          6. **Provide feedback** - Use GitHub's PR review system to provide comprehensive feedback:
             
             **How PR reviews work**: When you submit a PR review, it can include:
             - **Inline comments** - Comments on specific lines of code (shown in the "Files changed" tab)
             - **Review summary** - An overall comment with your review state (approve/request changes/comment)
             
             **Submit a complete PR review**:
             
             **If you have inline comments** (recommended for thorough reviews):
             - Use `gh api` to submit a review that includes both inline comments and a summary in one API call
             - Create a JSON file with your review data, then submit it:
               ```bash
               # Create review.json with your review
               cat > review.json << 'EOF'
               {
                 "event": "APPROVE",
                 "body": "Your review summary here",
                 "comments": [
                   {
                     "path": "path/to/file",
                     "position": 42,
                     "body": "Your inline comment about this line"
                   },
                   {
                     "path": "another/file.go",
                     "position": 15,
                     "body": "Another inline comment"
                   }
                 ]
               }
               EOF
               
               # Submit the review
               gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
                 -X POST \
                 -H "Accept: application/vnd.github+json" \
                 --input review.json
               ```
             - Replace `event` in the JSON with:
               - `"APPROVE"` - To approve the PR
               - `"REQUEST_CHANGES"` - To request changes  
               - `"COMMENT"` - For comment-only review
             - The `comments` array contains all your inline comments - add one object per comment
             - For comments on new code, use `position` (1-based line number relative to the diff)
             - For comments on old code (deleted lines), use `line` instead of `position`
             - For multi-line comments, include both `start_line` and `line` parameters
             - **Important**: All inline comments and the review summary are submitted together in one review
             
             **If you have no inline comments** (simple review):
             - You can use the simpler `gh pr review` command:
               - **Approve**: `gh pr review ${{ github.event.pull_request.number }} --approve --body "Your review summary"`
               - **Request changes**: `gh pr review ${{ github.event.pull_request.number }} --request-changes --body "Your review summary"`
               - **Comment only**: `gh pr review ${{ github.event.pull_request.number }} --comment --body "Your review summary"`
             - However, for thorough reviews, you should add inline comments for specific code issues
             
             **Review summary body should include**:
             - Summary of what the PR does and its purpose
             - Overall assessment (what's good, what needs work)
             - Key concerns or suggestions (reference inline comments if applicable)
             - Positive aspects of the changes
             - Next steps or recommendations
             - End with the footer: `---\n*Comment by Claude Code* | ðŸš€ if perfect, ðŸ‘ if helpful, ðŸ‘Ž if not | Type \`@claude\` to interact further`
             
             **Best practices**:
             - Be thorough: add inline comments for all significant issues you find
             - Be constructive: explain why something should change, not just that it should
             - Be specific: reference exact lines and provide concrete suggestions
             - Be balanced: highlight positive aspects, not just problems
             - Focus on significant issues: don't nitpick minor style preferences unless they're part of the project's standards
             - Submit everything in one review: include all inline comments and the summary in a single API call

          **Important**: The footer should be included in your PR review summary body (the `--body` parameter), not in inline comments.

          ${{ inputs.additional-instructions }}
        claude_args: |
          ${{ inputs.allowed-tools != '' && format('--allowedTools {0}', inputs.allowed-tools) || '' }}
          --mcp-config '${{ inputs.mcp-servers }}'
          --model ${{ inputs.model }}
