# Composite Action for PR review with Claude
#
# Usage:
#   - uses: your-org/ai-github-actions/workflows/pr-review@v1
#     with:
#       claude-oauth-token: ${{ secrets.CLAUDE_OAUTH_TOKEN }}
#       github-token: ${{ github.token }}
#
name: "Claude PR Review"
description: "Review pull requests using Claude"

branding:
  icon: "git-pull-request"
  color: "purple"

inputs:
  claude-oauth-token:
    description: "Claude OAuth token for authentication"
    required: true

  github-token:
    description: "GitHub token for Claude to operate with"
    required: true

  model:
    description: "Model to use for Claude"
    required: false
    default: "claude-sonnet-4-20250514"

  allowed-tools:
    description: "Comma-separated list of allowed tools for Claude"
    required: false
    default: "Edit,MultiEdit,Glob,Grep,LS,Read,Write,WebSearch,WebFetch,mcp__github_comment__update_claude_comment,mcp__github_ci__get_ci_status,mcp__github_ci__get_workflow_run_details,mcp__github_ci__download_job_log,Bash(git add:*),Bash(git commit:*),Bash(git push:*),Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(git rm:*),Bash(gh pr review:*),Bash(gh pr comment:*),Bash(gh api:*),Bash,mcp__agents-md-generator__generate_agents_md,mcp__agents-md-generator,mcp__public-code-search__search_code"

  extra-allowed-tools:
    description: "Additional comma-separated list of allowed tools (concatenated with allowed-tools)"
    required: false
    default: ""

  additional-instructions:
    description: "Additional instructions to include in the prompt"
    required: false
    default: ""

  track-progress:
    description: "Whether Claude should track progress with visual indicators"
    required: false
    default: "true"

  mcp-servers:
    description: "MCP server configuration JSON"
    required: false
    default: '{"mcpServers":{"agents-md-generator":{"type":"http","url":"https://agents-md-generator.fastmcp.app/mcp"},"public-code-search":{"type":"http","url":"https://public-code-search.fastmcp.app/mcp"}}}'

outputs:
  conclusion:
    description: "The conclusion of the Claude Code run"
    value: ${{ steps.claude.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Run Claude for PR Review
      id: claude
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude-oauth-token }}
        github_token: ${{ inputs.github-token }}
        track_progress: ${{ inputs.track-progress }}
        prompt: |
          ## GitHub Context
          - Repository: ${{ github.repository }}
          - PR Number: #${{ github.event.pull_request.number }}
          - PR Title: ${{ github.event.pull_request.title }}
          - PR Author: ${{ github.event.pull_request.user.login }}
          - Base Branch: ${{ github.event.pull_request.base.ref }}
          - Head Branch: ${{ github.event.pull_request.head.ref }}
          - PR Body:
          ```
          ${{ github.event.pull_request.body }}
          ```

          ## Instructions
          
          ### Getting Started
          **First, get repository context**: Use the `mcp__agents-md-generator__generate_agents_md` tool to generate a repository summary. This will give you essential context about the codebase structure, technologies used, and project conventions. Call this tool at the start of your investigation.
          
          **If you encounter any issues using tools** (e.g., tool not found, permission errors, API failures), mention this in your review summary with a link to the support channel: https://your-slack-channel-link

          ### Investigation Approach
          **Be extremely thorough in your investigations**. Don't rush to conclusions. Take time to:
          - Understand the full context of the repository
          - Review all modified files and related code
          - Check for related issues, PRs, and discussions
          - Consider edge cases, performance, and security implications
          - Gather all relevant information before providing feedback
          
          **Available tools for investigation**:
          - **`mcp__public-code-search__search_code`**: Use this to search for code patterns in OTHER repositories (external libraries, modules, or dependencies). The current repository is cloned locally, so use `Grep` or `Read` for searching within this repo. Use `search_code` for finding similar implementations in other projects, checking how other repositories handle similar patterns, or understanding library APIs.
          - **`WebSearch`**: Use for searching the web for documentation, best practices, or solutions to specific problems.
          - **`WebFetch`**: Use to fetch and read content from URLs (documentation, API references, etc.).

          Review this pull request with a focus on **specific, objective insights** based on codebase context:

          ## Review Process

          1. **Understand the broader context**:
             - Review similar code patterns elsewhere in the codebase for consistency
             - Check how similar features are implemented in other files/modules
             - Understand the change's role in the larger system architecture
             - Identify related code that might be affected or should be updated

          2. **Review code consistency**:
             - Compare coding patterns, naming conventions, and structure with existing code
             - Check if error handling follows established patterns
             - Verify that the code matches the project's style guide and conventions
             - Look for deviations from established patterns that should be aligned

          3. **Check call sites and usage**:
             - Find all places where changed functions/methods are called
             - Verify that call sites are compatible with the changes
             - Check if other code needs updates to work with these changes
             - Identify any breaking changes or migration needs

          4. **Review documentation**:
             - Check if feature documentation exists and is accurate
             - Verify that API documentation reflects the changes
             - Look for inline code comments that need updates
             - Check README files, user guides, and other docs that reference this feature

          5. **Verify test coverage**:
             - Check if tests cover the new/changed functionality
             - Verify tests follow the same patterns as existing tests
             - Look for edge cases that aren't covered
             - Check if integration tests are needed

          6. **Identify specific issues**:
             - Look for bugs, logic errors, or incorrect implementations
             - Check for security vulnerabilities or unsafe patterns
             - Identify performance issues or inefficiencies
             - Find missing error handling or edge case coverage

          ## Feedback Guidelines

          **DO:**
          - Provide specific, actionable feedback on concrete issues
          - Reference exact lines of code and specific problems
          - Compare with existing code patterns in the repository
          - Point out inconsistencies with codebase conventions
          - Identify missing documentation or outdated docs
          - Note call sites that need updates
          - Suggest specific code changes or fixes

          **DO NOT:**
          - Provide general summaries or explanations of what the PR does
          - Praise or compliment the changes ("good addition", "nice work", etc.)
          - Make broad comments about potential system impacts
          - Question the intentions behind the changes
          - Provide feedback that isn't tied to specific code issues
          - Write general observations without concrete examples

          **Focus on objective, fact-based insights** that help improve code quality, consistency, and correctness.

          ## Submitting Your Review

          Use GitHub's PR review system to provide feedback:
             
             **How PR reviews work**: When you submit a PR review, it can include:
             - **Inline comments** - Comments on specific lines of code (shown in the "Files changed" tab)
             - **Review summary** - An overall comment with your review state (approve/request changes/comment)
             
             **Submit a complete PR review**:
             
             **If you have inline comments** (recommended for thorough reviews):
             
             **Create a pending review and add comments to it** (all grouped in one review):
             
             **Step 1: Create a pending review**:
             ```bash
             # Get HEAD commit SHA
             HEAD_SHA=$(gh pr view ${{ github.event.pull_request.number }} --json headRefOid --jq .headRefOid)
             
             # Create a pending review and save the review ID
             REVIEW_ID=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
               -X POST \
               -f commit_id="$HEAD_SHA" \
               -f event="PENDING" \
               --jq .id)
             
             echo "Created pending review: $REVIEW_ID"
             ```
             
             **Step 2: Add inline comments to the pending review** (repeat for each issue):
             
             For each issue you find:
             ```bash
             # Get the file's diff patch
             FILE="path/to/file"
             PATCH=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files --paginate --jq \
               '.[] | select(.filename=="'"$FILE"'") | .patch')
             
             # Calculate the position (find the line with a unique snippet from the changed line)
             # Position is 1-based, counting from the first line after the @@ hunk header
             POS=$(echo "$PATCH" | awk 'BEGIN{pos=0} {pos++; if ($0 ~ /^\+/ && index($0, "<unique-snippet-from-the-changed-line>")>0) {print pos; exit}}')
             
             # Verify position was found
             if [ -z "$POS" ]; then
               echo "Error: Could not find position for $FILE"
               exit 1
             fi
             
             # Add the comment (it will automatically be associated with the pending review)
             gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments \
               -X POST \
               -f commit_id="$HEAD_SHA" \
               -f path="$FILE" \
               -f position="$POS" \
               --raw-field body=$'### Issue: Specific problem\n\n**Problem**: Concrete issue with this code\n\n**Expected**: What should happen\n\n**Fix**: Specific code change\n\n```go\n// example of correct pattern\n```'
             ```
             
             **Important**: 
             - Use a unique snippet from the actual changed line (not the entire line if it's very long)
             - The snippet should be unique enough to match only the line you want
             - Position must be calculated from the full patch (including the @@ header)
             - All comments added while a pending review exists will be grouped with that review
             
             Repeat this for each inline comment you want to add.
             
             **Step 3: Submit the review** (after adding all comments):
             ```bash
             # Submit the review with your summary (this will include all pending comments)
             gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews/$REVIEW_ID \
               -X PUT \
               -f event="REQUEST_CHANGES" \
               --raw-field body=$'Your review summary here\n\n---\n*Comment by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type `@claude` to interact further'
             
             # Or use "APPROVE" or "COMMENT" instead of "REQUEST_CHANGES"
             ```
             
             **Important rules**:
             - **Always use `position`** (calculated from the diff patch as shown)
             - Position is the line number in the unified diff (1-based, from first `@@` hunk header)
             - Only comment on lines that were actually changed (lines with `+` in the diff)
             - Use structured comment format: specific problem, expected behavior, fix
             - Reference existing code patterns when suggesting fixes
             - All comments added to the same REVIEW_ID will be grouped in one review
             - Focus on objective issues - no general feedback or explanations
             
             **If you have no inline comments** (simple review):
             - You can use the simpler `gh pr review` command, but be careful with special characters:
               ```bash
               # Use --body-file for complex text to avoid shell escaping issues
               echo "Your review summary here" > review_body.txt
               gh pr review ${{ github.event.pull_request.number }} --request-changes --body-file review_body.txt
               ```
               - Or use `gh api` with `--raw-field` for better control:
                 ```bash
                 gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
                   -X POST \
                   -f event="REQUEST_CHANGES" \
                   --raw-field body="Your review summary here"
                 ```
             - However, for thorough reviews, you should add inline comments for specific code issues
             
             **Review summary body should include**:
             - List of specific issues found (reference inline comments)
             - Code consistency issues compared to existing codebase patterns
             - Documentation gaps or inaccuracies identified
             - Call sites or related code that needs updates
             - Test coverage gaps
             - End with the footer: `---\n*Comment by Claude Code* | 🚀 if perfect, 👍 if helpful, 👎 if not | Type \`@claude\` to interact further`
             
             **Review summary guidelines**:
             - Only include specific, objective issues - no general summaries or praises
             - Reference inline comments by file/line when applicable
             - Focus on actionable items that need to be addressed
             - If no issues found, simply approve with minimal comment (just the footer)
             - Don't explain what the PR does - focus on what needs to be fixed or improved
             - Submit everything in one review: include all inline comments and the summary in a single API call

          **Important**: The footer should be included in your PR review summary body (the `--body` parameter), not in inline comments.

          ${{ inputs.additional-instructions }}
        claude_args: |
          ${{ inputs.allowed-tools != '' && inputs.extra-allowed-tools != '' && format('--allowedTools {0},{1}', inputs.allowed-tools, inputs.extra-allowed-tools) || (inputs.allowed-tools != '' && format('--allowedTools {0}', inputs.allowed-tools) || (inputs.extra-allowed-tools != '' && format('--allowedTools {0}', inputs.extra-allowed-tools) || '')) }}
          --mcp-config '${{ inputs.mcp-servers }}'
          --model ${{ inputs.model }}
